// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: PassNFC.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// An object that represents the near-field communication (NFC) payload the device passes to an Apple Pay terminal.
struct PBPassNFC: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// (Required) A Base64-encoded X.509 SubjectPublicKeyInfo containing an ECDH public key for curve secp256r1.
  /// Include only the Base64 body of the PEM (exclude the BEGIN/END lines).
  /// The public encryption key is used by the Value Added Services protocol.
  var encryptionPublicKey: String = String()

  /// (Required) The payload the device transmits to the Apple Pay terminal. The size must be no more than 64 bytes.
  /// The system truncates messages longer than 64 bytes.
  var message: String = String()

  /// A Boolean value that indicates whether the NFC pass requires authentication. The default value is false.
  /// A value of true requires the user to authenticate for each use of the NFC pass. This key is valid in
  /// iOS 13.1 and later. Set sharingProhibited to true to prevent users from sharing passes with older iOS
  /// versions and bypassing the authentication requirement.
  var requiresAuthentication: Bool = false

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "pass"

extension PBPassNFC: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".PassNFC"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}encryption_public_key\0\u{1}message\0\u{3}requires_authentication\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.encryptionPublicKey) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.message) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.requiresAuthentication) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.encryptionPublicKey.isEmpty {
      try visitor.visitSingularStringField(value: self.encryptionPublicKey, fieldNumber: 1)
    }
    if !self.message.isEmpty {
      try visitor.visitSingularStringField(value: self.message, fieldNumber: 2)
    }
    if self.requiresAuthentication != false {
      try visitor.visitSingularBoolField(value: self.requiresAuthentication, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: PBPassNFC, rhs: PBPassNFC) -> Bool {
    if lhs.encryptionPublicKey != rhs.encryptionPublicKey {return false}
    if lhs.message != rhs.message {return false}
    if lhs.requiresAuthentication != rhs.requiresAuthentication {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
