// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: PassBeacon.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// An message that represents the identifier of a Bluetooth Low Energy beacon the system uses to show a
/// relevant pass.
struct PBPassBeacon: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// (Required) The unique identifier of a Bluetooth Low Energy location beacon.
  var proximityUuid: String = String()

  /// The major identifier of a Bluetooth Low Energy location beacon.
  var major: UInt32 {
    get {return _major ?? 0}
    set {_major = newValue}
  }
  /// Returns true if `major` has been explicitly set.
  var hasMajor: Bool {return self._major != nil}
  /// Clears the value of `major`. Subsequent reads from it will return its default value.
  mutating func clearMajor() {self._major = nil}

  /// The minor identifier of a Bluetooth Low Energy location beacon.
  var minor: UInt32 {
    get {return _minor ?? 0}
    set {_minor = newValue}
  }
  /// Returns true if `minor` has been explicitly set.
  var hasMinor: Bool {return self._minor != nil}
  /// Clears the value of `minor`. Subsequent reads from it will return its default value.
  mutating func clearMinor() {self._minor = nil}

  /// The text to display on the lock screen when the pass is relevant.
  /// For example, a description of a nearby location.
  var relevantText: String {
    get {return _relevantText ?? String()}
    set {_relevantText = newValue}
  }
  /// Returns true if `relevantText` has been explicitly set.
  var hasRelevantText: Bool {return self._relevantText != nil}
  /// Clears the value of `relevantText`. Subsequent reads from it will return its default value.
  mutating func clearRelevantText() {self._relevantText = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _major: UInt32? = nil
  fileprivate var _minor: UInt32? = nil
  fileprivate var _relevantText: String? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "pass"

extension PBPassBeacon: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".PassBeacon"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}proximity_uuid\0\u{1}major\0\u{1}minor\0\u{3}relevant_text\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.proximityUuid) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self._major) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self._minor) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self._relevantText) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.proximityUuid.isEmpty {
      try visitor.visitSingularStringField(value: self.proximityUuid, fieldNumber: 1)
    }
    try { if let v = self._major {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._minor {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._relevantText {
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: PBPassBeacon, rhs: PBPassBeacon) -> Bool {
    if lhs.proximityUuid != rhs.proximityUuid {return false}
    if lhs._major != rhs._major {return false}
    if lhs._minor != rhs._minor {return false}
    if lhs._relevantText != rhs._relevantText {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
