// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: Pass.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// A message that represents a pass.
struct PBPass: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// (Required) An alphanumeric serial number. The combination of the serial number and pass type identifier
  /// needs to be unique for each pass.
  var serialNumber: String {
    get {return _storage._serialNumber}
    set {_uniqueStorage()._serialNumber = newValue}
  }

  /// The URL for a web service that you use to update or personalize the pass. The URL can include an optional
  /// port number.
  var webServiceURL: String {
    get {return _storage._webServiceURL ?? String()}
    set {_uniqueStorage()._webServiceURL = newValue}
  }
  /// Returns true if `webServiceURL` has been explicitly set.
  var hasWebServiceURL: Bool {return _storage._webServiceURL != nil}
  /// Clears the value of `webServiceURL`. Subsequent reads from it will return its default value.
  mutating func clearWebServiceURL() {_uniqueStorage()._webServiceURL = nil}

  /// The authentication token to use with the web service in the webServiceURL key.
  var authenticationToken: String {
    get {return _storage._authenticationToken ?? String()}
    set {_uniqueStorage()._authenticationToken = newValue}
  }
  /// Returns true if `authenticationToken` has been explicitly set.
  var hasAuthenticationToken: Bool {return _storage._authenticationToken != nil}
  /// Clears the value of `authenticationToken`. Subsequent reads from it will return its default value.
  mutating func clearAuthenticationToken() {_uniqueStorage()._authenticationToken = nil}

  /// The pass type identifier that’s registered with Apple. The value needs to be the same as the distribution
  /// certificate that signs the pass.
  /// Required if not specified in the associated pkpasstemplate.
  var passTypeIdentifier: String {
    get {return _storage._passTypeIdentifier ?? String()}
    set {_uniqueStorage()._passTypeIdentifier = newValue}
  }
  /// Returns true if `passTypeIdentifier` has been explicitly set.
  var hasPassTypeIdentifier: Bool {return _storage._passTypeIdentifier != nil}
  /// Clears the value of `passTypeIdentifier`. Subsequent reads from it will return its default value.
  mutating func clearPassTypeIdentifier() {_uniqueStorage()._passTypeIdentifier = nil}

  /// The Team ID for the Apple Developer Program account that registered the pass type identifier.
  /// Required if not specified in the associated pkpasstemplate.
  var teamIdentifier: String {
    get {return _storage._teamIdentifier ?? String()}
    set {_uniqueStorage()._teamIdentifier = newValue}
  }
  /// Returns true if `teamIdentifier` has been explicitly set.
  var hasTeamIdentifier: Bool {return _storage._teamIdentifier != nil}
  /// Clears the value of `teamIdentifier`. Subsequent reads from it will return its default value.
  mutating func clearTeamIdentifier() {_uniqueStorage()._teamIdentifier = nil}

  /// The name of the organization.
  /// Required if not specified in the associated pkpasstemplate.
  var organizationName: String {
    get {return _storage._organizationName ?? String()}
    set {_uniqueStorage()._organizationName = newValue}
  }
  /// Returns true if `organizationName` has been explicitly set.
  var hasOrganizationName: Bool {return _storage._organizationName != nil}
  /// Clears the value of `organizationName`. Subsequent reads from it will return its default value.
  mutating func clearOrganizationName() {_uniqueStorage()._organizationName = nil}

  /// A short description that iOS accessibility technologies use for a pass.
  /// Required if not specified in the associated pkpasstemplate.
  var description_p: String {
    get {return _storage._description_p ?? String()}
    set {_uniqueStorage()._description_p = newValue}
  }
  /// Returns true if `description_p` has been explicitly set.
  var hasDescription_p: Bool {return _storage._description_p != nil}
  /// Clears the value of `description_p`. Subsequent reads from it will return its default value.
  mutating func clearDescription_p() {_uniqueStorage()._description_p = nil}

  /// A Boolean value introduced in iOS 11 that controls whether to show the Share button on the back of a pass.
  /// A value of true removes the button. The default value is false. This flag has no effect in earlier versions
  /// of iOS, nor does it prevent sharing the pass in some other way.
  var sharingProhibited: Bool {
    get {return _storage._sharingProhibited ?? false}
    set {_uniqueStorage()._sharingProhibited = newValue}
  }
  /// Returns true if `sharingProhibited` has been explicitly set.
  var hasSharingProhibited: Bool {return _storage._sharingProhibited != nil}
  /// Clears the value of `sharingProhibited`. Subsequent reads from it will return its default value.
  mutating func clearSharingProhibited() {_uniqueStorage()._sharingProhibited = nil}

  /// The fields of a pass.
  var fields: PBPassFields {
    get {return _storage._fields ?? PBPassFields()}
    set {_uniqueStorage()._fields = newValue}
  }
  /// Returns true if `fields` has been explicitly set.
  var hasFields: Bool {return _storage._fields != nil}
  /// Clears the value of `fields`. Subsequent reads from it will return its default value.
  mutating func clearFields() {_uniqueStorage()._fields = nil}

  /// An array of App Store identifiers for apps associated with the pass. The associated app on a device is the
  /// first item in the array that’s compatible with that device. A link to launch the app is on the back of the
  /// pass. If the app isn’t installed, the link opens the App Store.
  var associatedStoreIdentifiers: [Int32] {
    get {return _storage._associatedStoreIdentifiers}
    set {_uniqueStorage()._associatedStoreIdentifiers = newValue}
  }

  /// An array of additional App Store identifiers for apps associated with the pass. The associated app on a device
  /// is the first item in the array that’s compatible with that device. This key works only for poster event tickets.
  /// A link to launch the app is in the event guide of the pass. If the app isn’t installed, the link opens the
  /// App Store.
  var auxiliaryStoreIdentifiers: [Int32] {
    get {return _storage._auxiliaryStoreIdentifiers}
    set {_uniqueStorage()._auxiliaryStoreIdentifiers = newValue}
  }

  /// The date and time the pass expires.
  var expirationDate: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _storage._expirationDate ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_uniqueStorage()._expirationDate = newValue}
  }
  /// Returns true if `expirationDate` has been explicitly set.
  var hasExpirationDate: Bool {return _storage._expirationDate != nil}
  /// Clears the value of `expirationDate`. Subsequent reads from it will return its default value.
  mutating func clearExpirationDate() {_uniqueStorage()._expirationDate = nil}

  /// A Boolean value that indicates that the pass is void, such as a redeemed, one-time-use coupon.
  /// The default value is false.
  var voided: Bool {
    get {return _storage._voided ?? false}
    set {_uniqueStorage()._voided = newValue}
  }
  /// Returns true if `voided` has been explicitly set.
  var hasVoided: Bool {return _storage._voided != nil}
  /// Clears the value of `voided`. Subsequent reads from it will return its default value.
  mutating func clearVoided() {_uniqueStorage()._voided = nil}

  /// An array of message that represent possible barcodes on a pass. The system uses the first displayable barcode
  /// for the device.
  var barcodes: [PBPassBarcode] {
    get {return _storage._barcodes}
    set {_uniqueStorage()._barcodes = newValue}
  }

  /// The maximum distance, in meters, from a location in the locations array at which the pass is relevant.
  /// The system uses the smaller of this distance or the default distance.
  var maxDistance: Double {
    get {return _storage._maxDistance ?? 0}
    set {_uniqueStorage()._maxDistance = newValue}
  }
  /// Returns true if `maxDistance` has been explicitly set.
  var hasMaxDistance: Bool {return _storage._maxDistance != nil}
  /// Clears the value of `maxDistance`. Subsequent reads from it will return its default value.
  mutating func clearMaxDistance() {_uniqueStorage()._maxDistance = nil}

  /// The date and time when the pass becomes relevant, as a W3C timestamp, such as the start time of a movie.
  /// The value needs to be a complete date that includes hours and minutes, and may optionally include seconds.
  var relevantDate: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _storage._relevantDate ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_uniqueStorage()._relevantDate = newValue}
  }
  /// Returns true if `relevantDate` has been explicitly set.
  var hasRelevantDate: Bool {return _storage._relevantDate != nil}
  /// Clears the value of `relevantDate`. Subsequent reads from it will return its default value.
  mutating func clearRelevantDate() {_uniqueStorage()._relevantDate = nil}

  /// An array of objects that represent date intervals that the system uses to show a relevant pass.
  var relevantDates: [PBPassRelevantDate] {
    get {return _storage._relevantDates}
    set {_uniqueStorage()._relevantDates = newValue}
  }

  /// An array of up to 10 objects that represent geographic locations the system uses to show a relevant pass.
  var locations: [PBPassLocation] {
    get {return _storage._locations}
    set {_uniqueStorage()._locations = newValue}
  }

  /// An array of objects that represent the identity of Bluetooth Low Energy beacons the system uses to show a
  /// relevant pass.
  var beacons: [PBPassBeacon] {
    get {return _storage._beacons}
    set {_uniqueStorage()._beacons = newValue}
  }

  /// A background color for the pass.
  var backgroundColor: PBPassColor {
    get {return _storage._backgroundColor ?? PBPassColor()}
    set {_uniqueStorage()._backgroundColor = newValue}
  }
  /// Returns true if `backgroundColor` has been explicitly set.
  var hasBackgroundColor: Bool {return _storage._backgroundColor != nil}
  /// Clears the value of `backgroundColor`. Subsequent reads from it will return its default value.
  mutating func clearBackgroundColor() {_uniqueStorage()._backgroundColor = nil}

  /// A foreground color for the pass.
  var foregroundColor: PBPassColor {
    get {return _storage._foregroundColor ?? PBPassColor()}
    set {_uniqueStorage()._foregroundColor = newValue}
  }
  /// Returns true if `foregroundColor` has been explicitly set.
  var hasForegroundColor: Bool {return _storage._foregroundColor != nil}
  /// Clears the value of `foregroundColor`. Subsequent reads from it will return its default value.
  mutating func clearForegroundColor() {_uniqueStorage()._foregroundColor = nil}

  /// A color for the label text of the pass. If you don’t provide a value, the system determines the label color.
  var labelColor: PBPassColor {
    get {return _storage._labelColor ?? PBPassColor()}
    set {_uniqueStorage()._labelColor = newValue}
  }
  /// Returns true if `labelColor` has been explicitly set.
  var hasLabelColor: Bool {return _storage._labelColor != nil}
  /// Clears the value of `labelColor`. Subsequent reads from it will return its default value.
  mutating func clearLabelColor() {_uniqueStorage()._labelColor = nil}

  /// A strip color for the pass.
  var stripColor: PBPassColor {
    get {return _storage._stripColor ?? PBPassColor()}
    set {_uniqueStorage()._stripColor = newValue}
  }
  /// Returns true if `stripColor` has been explicitly set.
  var hasStripColor: Bool {return _storage._stripColor != nil}
  /// Clears the value of `stripColor`. Subsequent reads from it will return its default value.
  mutating func clearStripColor() {_uniqueStorage()._stripColor = nil}

  /// A background color for the footer of the pass.
  /// This key works only for poster event tickets.
  var footerBackgroundColor: PBPassColor {
    get {return _storage._footerBackgroundColor ?? PBPassColor()}
    set {_uniqueStorage()._footerBackgroundColor = newValue}
  }
  /// Returns true if `footerBackgroundColor` has been explicitly set.
  var hasFooterBackgroundColor: Bool {return _storage._footerBackgroundColor != nil}
  /// Clears the value of `footerBackgroundColor`. Subsequent reads from it will return its default value.
  mutating func clearFooterBackgroundColor() {_uniqueStorage()._footerBackgroundColor = nil}

  /// A Boolean value that controls whether to display the header darkening gradient on poster event tickets.
  /// The default value is false.
  /// This key works only for poster event tickets.
  var suppressHeaderDarkening: Bool {
    get {return _storage._suppressHeaderDarkening ?? false}
    set {_uniqueStorage()._suppressHeaderDarkening = newValue}
  }
  /// Returns true if `suppressHeaderDarkening` has been explicitly set.
  var hasSuppressHeaderDarkening: Bool {return _storage._suppressHeaderDarkening != nil}
  /// Clears the value of `suppressHeaderDarkening`. Subsequent reads from it will return its default value.
  mutating func clearSuppressHeaderDarkening() {_uniqueStorage()._suppressHeaderDarkening = nil}

  /// A Boolean value that controls whether Wallet computes the foreground and label color that the pass uses.
  /// The system derives the background color from the background image of the pass.
  /// This key works only for poster event tickets.
  /// This key ignores the values that foregroundColor and labelColor specify.
  var useAutomaticColors: Bool {
    get {return _storage._useAutomaticColors ?? false}
    set {_uniqueStorage()._useAutomaticColors = newValue}
  }
  /// Returns true if `useAutomaticColors` has been explicitly set.
  var hasUseAutomaticColors: Bool {return _storage._useAutomaticColors != nil}
  /// Clears the value of `useAutomaticColors`. Subsequent reads from it will return its default value.
  mutating func clearUseAutomaticColors() {_uniqueStorage()._useAutomaticColors = nil}

  /// The text to display next to the logo on the pass.
  /// This key works only for poster event tickets.
  var eventLogoText: String {
    get {return _storage._eventLogoText ?? String()}
    set {_uniqueStorage()._eventLogoText = newValue}
  }
  /// Returns true if `eventLogoText` has been explicitly set.
  var hasEventLogoText: Bool {return _storage._eventLogoText != nil}
  /// Clears the value of `eventLogoText`. Subsequent reads from it will return its default value.
  mutating func clearEventLogoText() {_uniqueStorage()._eventLogoText = nil}

  /// The text to display next to the logo on the pass.
  /// This key doesn’t work for poster event tickets.
  var logoText: String {
    get {return _storage._logoText ?? String()}
    set {_uniqueStorage()._logoText = newValue}
  }
  /// Returns true if `logoText` has been explicitly set.
  var hasLogoText: Bool {return _storage._logoText != nil}
  /// Clears the value of `logoText`. Subsequent reads from it will return its default value.
  mutating func clearLogoText() {_uniqueStorage()._logoText = nil}

  /// An identifier the system uses to group related boarding passes or event tickets.
  /// Wallet displays passes with the same groupingIdentifier, passTypeIdentifier, and type as a group.
  /// Use this identifier to group passes that are tightly related, such as boarding passes for different
  /// connections on the same trip.
  var groupingIdentifier: String {
    get {return _storage._groupingIdentifier ?? String()}
    set {_uniqueStorage()._groupingIdentifier = newValue}
  }
  /// Returns true if `groupingIdentifier` has been explicitly set.
  var hasGroupingIdentifier: Bool {return _storage._groupingIdentifier != nil}
  /// Clears the value of `groupingIdentifier`. Subsequent reads from it will return its default value.
  mutating func clearGroupingIdentifier() {_uniqueStorage()._groupingIdentifier = nil}

  /// An object that contains the information to use for Value-Added Services protocol transactions.
  var nfc: PBPassNFC {
    get {return _storage._nfc ?? PBPassNFC()}
    set {_uniqueStorage()._nfc = newValue}
  }
  /// Returns true if `nfc` has been explicitly set.
  var hasNfc: Bool {return _storage._nfc != nil}
  /// Clears the value of `nfc`. Subsequent reads from it will return its default value.
  mutating func clearNfc() {_uniqueStorage()._nfc = nil}

  /// An array of schemes to validate the pass with. The system validates the pass and its contents to ensure they
  /// meet the schemes’ requirements, falling back to the designed type if validation fails for all the
  /// provided schemes.
  var preferredStyleSchemes: [String] {
    get {return _storage._preferredStyleSchemes}
    set {_uniqueStorage()._preferredStyleSchemes = newValue}
  }

  /// An object that contains machine-readable metadata the system uses to offer a pass and suggest related actions.
  var semantics: PBPassSemantics {
    get {return _storage._semantics ?? PBPassSemantics()}
    set {_uniqueStorage()._semantics = newValue}
  }
  /// Returns true if `semantics` has been explicitly set.
  var hasSemantics: Bool {return _storage._semantics != nil}
  /// Clears the value of `semantics`. Subsequent reads from it will return its default value.
  mutating func clearSemantics() {_uniqueStorage()._semantics = nil}

  /// A URL the system passes to the associated app from associatedStoreIdentifiers during launch.
  var appLaunchURL: String {
    get {return _storage._appLaunchURL ?? String()}
    set {_uniqueStorage()._appLaunchURL = newValue}
  }
  /// Returns true if `appLaunchURL` has been explicitly set.
  var hasAppLaunchURL: Bool {return _storage._appLaunchURL != nil}
  /// Clears the value of `appLaunchURL`. Subsequent reads from it will return its default value.
  mutating func clearAppLaunchURL() {_uniqueStorage()._appLaunchURL = nil}

  /// A URL for management.
  var managementURL: String {
    get {return _storage._managementURL ?? String()}
    set {_uniqueStorage()._managementURL = newValue}
  }
  /// Returns true if `managementURL` has been explicitly set.
  var hasManagementURL: Bool {return _storage._managementURL != nil}
  /// Clears the value of `managementURL`. Subsequent reads from it will return its default value.
  mutating func clearManagementURL() {_uniqueStorage()._managementURL = nil}

  /// A URL that links to your accessiblity content, or the venue’s.
  /// This key works only for poster event tickets.
  var accessibilityURL: String {
    get {return _storage._accessibilityURL ?? String()}
    set {_uniqueStorage()._accessibilityURL = newValue}
  }
  /// Returns true if `accessibilityURL` has been explicitly set.
  var hasAccessibilityURL: Bool {return _storage._accessibilityURL != nil}
  /// Clears the value of `accessibilityURL`. Subsequent reads from it will return its default value.
  mutating func clearAccessibilityURL() {_uniqueStorage()._accessibilityURL = nil}

  /// A URL that can link to experiences that someone can add to the pass.
  /// This key works only for poster event tickets.
  var addOnURL: String {
    get {return _storage._addOnURL ?? String()}
    set {_uniqueStorage()._addOnURL = newValue}
  }
  /// Returns true if `addOnURL` has been explicitly set.
  var hasAddOnURL: Bool {return _storage._addOnURL != nil}
  /// Clears the value of `addOnURL`. Subsequent reads from it will return its default value.
  mutating func clearAddOnURL() {_uniqueStorage()._addOnURL = nil}

  /// A URL that links to the bag policy of the venue for the event that the pass represents.
  /// This key works only for poster event tickets.
  var bagPolicyURL: String {
    get {return _storage._bagPolicyURL ?? String()}
    set {_uniqueStorage()._bagPolicyURL = newValue}
  }
  /// Returns true if `bagPolicyURL` has been explicitly set.
  var hasBagPolicyURL: Bool {return _storage._bagPolicyURL != nil}
  /// Clears the value of `bagPolicyURL`. Subsequent reads from it will return its default value.
  mutating func clearBagPolicyURL() {_uniqueStorage()._bagPolicyURL = nil}

  /// A URL that links to a site for ordering merchandise for the event that the pass represents.
  /// This key works only for poster event tickets.
  var merchandiseURL: String {
    get {return _storage._merchandiseURL ?? String()}
    set {_uniqueStorage()._merchandiseURL = newValue}
  }
  /// Returns true if `merchandiseURL` has been explicitly set.
  var hasMerchandiseURL: Bool {return _storage._merchandiseURL != nil}
  /// Clears the value of `merchandiseURL`. Subsequent reads from it will return its default value.
  mutating func clearMerchandiseURL() {_uniqueStorage()._merchandiseURL = nil}

  /// A URL that links to the food ordering page for the event that the pass represents.
  /// This key works only for poster event tickets.
  var orderFoodURL: String {
    get {return _storage._orderFoodURL ?? String()}
    set {_uniqueStorage()._orderFoodURL = newValue}
  }
  /// Returns true if `orderFoodURL` has been explicitly set.
  var hasOrderFoodURL: Bool {return _storage._orderFoodURL != nil}
  /// Clears the value of `orderFoodURL`. Subsequent reads from it will return its default value.
  mutating func clearOrderFoodURL() {_uniqueStorage()._orderFoodURL = nil}

  /// A URL that links to parking information for the event that the pass represents.
  /// This key works only for poster event tickets.
  var parkingInformationURL: String {
    get {return _storage._parkingInformationURL ?? String()}
    set {_uniqueStorage()._parkingInformationURL = newValue}
  }
  /// Returns true if `parkingInformationURL` has been explicitly set.
  var hasParkingInformationURL: Bool {return _storage._parkingInformationURL != nil}
  /// Clears the value of `parkingInformationURL`. Subsequent reads from it will return its default value.
  mutating func clearParkingInformationURL() {_uniqueStorage()._parkingInformationURL = nil}

  /// A URL that links to a site to purchase parking for the event that the pass represents.
  /// This key works only for poster event tickets.
  var purchaseParkingURL: String {
    get {return _storage._purchaseParkingURL ?? String()}
    set {_uniqueStorage()._purchaseParkingURL = newValue}
  }
  /// Returns true if `purchaseParkingURL` has been explicitly set.
  var hasPurchaseParkingURL: Bool {return _storage._purchaseParkingURL != nil}
  /// Clears the value of `purchaseParkingURL`. Subsequent reads from it will return its default value.
  mutating func clearPurchaseParkingURL() {_uniqueStorage()._purchaseParkingURL = nil}

  /// A URL that links to the selling flow for the ticket the pass represents.
  /// This key works only for poster event tickets.
  var sellURL: String {
    get {return _storage._sellURL ?? String()}
    set {_uniqueStorage()._sellURL = newValue}
  }
  /// Returns true if `sellURL` has been explicitly set.
  var hasSellURL: Bool {return _storage._sellURL != nil}
  /// Clears the value of `sellURL`. Subsequent reads from it will return its default value.
  mutating func clearSellURL() {_uniqueStorage()._sellURL = nil}

  /// A URL that links to the transferring flow for the ticket that the pass represents.
  /// This key works only for poster event tickets.
  var transferURL: String {
    get {return _storage._transferURL ?? String()}
    set {_uniqueStorage()._transferURL = newValue}
  }
  /// Returns true if `transferURL` has been explicitly set.
  var hasTransferURL: Bool {return _storage._transferURL != nil}
  /// Clears the value of `transferURL`. Subsequent reads from it will return its default value.
  mutating func clearTransferURL() {_uniqueStorage()._transferURL = nil}

  /// A URL that links to information about transit options in the area of the event that the pass represents.
  /// This key works only for poster event tickets.
  var transitInformationURL: String {
    get {return _storage._transitInformationURL ?? String()}
    set {_uniqueStorage()._transitInformationURL = newValue}
  }
  /// Returns true if `transitInformationURL` has been explicitly set.
  var hasTransitInformationURL: Bool {return _storage._transitInformationURL != nil}
  /// Clears the value of `transitInformationURL`. Subsequent reads from it will return its default value.
  mutating func clearTransitInformationURL() {_uniqueStorage()._transitInformationURL = nil}

  /// The preferred email address to contact the venue, event, or issuer.
  /// This key works only for poster event tickets.
  var contactVenueEmail: String {
    get {return _storage._contactVenueEmail ?? String()}
    set {_uniqueStorage()._contactVenueEmail = newValue}
  }
  /// Returns true if `contactVenueEmail` has been explicitly set.
  var hasContactVenueEmail: Bool {return _storage._contactVenueEmail != nil}
  /// Clears the value of `contactVenueEmail`. Subsequent reads from it will return its default value.
  mutating func clearContactVenueEmail() {_uniqueStorage()._contactVenueEmail = nil}

  /// The phone number for contacting the venue, event, or issuer.
  /// This key works only for poster event tickets.
  var contactVenuePhoneNumber: String {
    get {return _storage._contactVenuePhoneNumber ?? String()}
    set {_uniqueStorage()._contactVenuePhoneNumber = newValue}
  }
  /// Returns true if `contactVenuePhoneNumber` has been explicitly set.
  var hasContactVenuePhoneNumber: Bool {return _storage._contactVenuePhoneNumber != nil}
  /// Clears the value of `contactVenuePhoneNumber`. Subsequent reads from it will return its default value.
  mutating func clearContactVenuePhoneNumber() {_uniqueStorage()._contactVenuePhoneNumber = nil}

  /// A URL that links to the website of the venue, event, or issuer.
  /// This key works only for poster event tickets.
  var contactVenueWebsite: String {
    get {return _storage._contactVenueWebsite ?? String()}
    set {_uniqueStorage()._contactVenueWebsite = newValue}
  }
  /// Returns true if `contactVenueWebsite` has been explicitly set.
  var hasContactVenueWebsite: Bool {return _storage._contactVenueWebsite != nil}
  /// Clears the value of `contactVenueWebsite`. Subsequent reads from it will return its default value.
  mutating func clearContactVenueWebsite() {_uniqueStorage()._contactVenueWebsite = nil}

  /// A URL that links to directions for the event.
  /// This key works only for poster event tickets.
  var directionsInformationURL: String {
    get {return _storage._directionsInformationURL ?? String()}
    set {_uniqueStorage()._directionsInformationURL = newValue}
  }
  /// Returns true if `directionsInformationURL` has been explicitly set.
  var hasDirectionsInformationURL: Bool {return _storage._directionsInformationURL != nil}
  /// Clears the value of `directionsInformationURL`. Subsequent reads from it will return its default value.
  mutating func clearDirectionsInformationURL() {_uniqueStorage()._directionsInformationURL = nil}

  /// A URL for changing the seat for the ticket.
  var changeSeatURL: String {
    get {return _storage._changeSeatURL ?? String()}
    set {_uniqueStorage()._changeSeatURL = newValue}
  }
  /// Returns true if `changeSeatURL` has been explicitly set.
  var hasChangeSeatURL: Bool {return _storage._changeSeatURL != nil}
  /// Clears the value of `changeSeatURL`. Subsequent reads from it will return its default value.
  mutating func clearChangeSeatURL() {_uniqueStorage()._changeSeatURL = nil}

  /// A URL for in-flight entertainment.
  var entertainmentURL: String {
    get {return _storage._entertainmentURL ?? String()}
    set {_uniqueStorage()._entertainmentURL = newValue}
  }
  /// Returns true if `entertainmentURL` has been explicitly set.
  var hasEntertainmentURL: Bool {return _storage._entertainmentURL != nil}
  /// Clears the value of `entertainmentURL`. Subsequent reads from it will return its default value.
  mutating func clearEntertainmentURL() {_uniqueStorage()._entertainmentURL = nil}

  /// A URL for adding checked bags for the ticket.
  var purchaseAdditionalBaggageURL: String {
    get {return _storage._purchaseAdditionalBaggageURL ?? String()}
    set {_uniqueStorage()._purchaseAdditionalBaggageURL = newValue}
  }
  /// Returns true if `purchaseAdditionalBaggageURL` has been explicitly set.
  var hasPurchaseAdditionalBaggageURL: Bool {return _storage._purchaseAdditionalBaggageURL != nil}
  /// Clears the value of `purchaseAdditionalBaggageURL`. Subsequent reads from it will return its default value.
  mutating func clearPurchaseAdditionalBaggageURL() {_uniqueStorage()._purchaseAdditionalBaggageURL = nil}

  /// A URL that links to information to purchase lounge access.
  var purchaseLoungeAccessURL: String {
    get {return _storage._purchaseLoungeAccessURL ?? String()}
    set {_uniqueStorage()._purchaseLoungeAccessURL = newValue}
  }
  /// Returns true if `purchaseLoungeAccessURL` has been explicitly set.
  var hasPurchaseLoungeAccessURL: Bool {return _storage._purchaseLoungeAccessURL != nil}
  /// Clears the value of `purchaseLoungeAccessURL`. Subsequent reads from it will return its default value.
  mutating func clearPurchaseLoungeAccessURL() {_uniqueStorage()._purchaseLoungeAccessURL = nil}

  /// A URL for purchasing in-flight wifi.
  var purchaseWifiURL: String {
    get {return _storage._purchaseWifiURL ?? String()}
    set {_uniqueStorage()._purchaseWifiURL = newValue}
  }
  /// Returns true if `purchaseWifiURL` has been explicitly set.
  var hasPurchaseWifiURL: Bool {return _storage._purchaseWifiURL != nil}
  /// Clears the value of `purchaseWifiURL`. Subsequent reads from it will return its default value.
  mutating func clearPurchaseWifiURL() {_uniqueStorage()._purchaseWifiURL = nil}

  /// A URL for upgrading the flight.
  var upgradeURL: String {
    get {return _storage._upgradeURL ?? String()}
    set {_uniqueStorage()._upgradeURL = newValue}
  }
  /// Returns true if `upgradeURL` has been explicitly set.
  var hasUpgradeURL: Bool {return _storage._upgradeURL != nil}
  /// Clears the value of `upgradeURL`. Subsequent reads from it will return its default value.
  mutating func clearUpgradeURL() {_uniqueStorage()._upgradeURL = nil}

  /// A URL for registering a service animal.
  var registerServiceAnimalURL: String {
    get {return _storage._registerServiceAnimalURL ?? String()}
    set {_uniqueStorage()._registerServiceAnimalURL = newValue}
  }
  /// Returns true if `registerServiceAnimalURL` has been explicitly set.
  var hasRegisterServiceAnimalURL: Bool {return _storage._registerServiceAnimalURL != nil}
  /// Clears the value of `registerServiceAnimalURL`. Subsequent reads from it will return its default value.
  mutating func clearRegisterServiceAnimalURL() {_uniqueStorage()._registerServiceAnimalURL = nil}

  /// A URL to report a lost bag.
  var reportLostBagURL: String {
    get {return _storage._reportLostBagURL ?? String()}
    set {_uniqueStorage()._reportLostBagURL = newValue}
  }
  /// Returns true if `reportLostBagURL` has been explicitly set.
  var hasReportLostBagURL: Bool {return _storage._reportLostBagURL != nil}
  /// Clears the value of `reportLostBagURL`. Subsequent reads from it will return its default value.
  mutating func clearReportLostBagURL() {_uniqueStorage()._reportLostBagURL = nil}

  /// A URL to request a wheel chair.
  var requestWheelchairURL: String {
    get {return _storage._requestWheelchairURL ?? String()}
    set {_uniqueStorage()._requestWheelchairURL = newValue}
  }
  /// Returns true if `requestWheelchairURL` has been explicitly set.
  var hasRequestWheelchairURL: Bool {return _storage._requestWheelchairURL != nil}
  /// Clears the value of `requestWheelchairURL`. Subsequent reads from it will return its default value.
  mutating func clearRequestWheelchairURL() {_uniqueStorage()._requestWheelchairURL = nil}

  /// The email for the transit provider.
  var transitProviderEmail: String {
    get {return _storage._transitProviderEmail ?? String()}
    set {_uniqueStorage()._transitProviderEmail = newValue}
  }
  /// Returns true if `transitProviderEmail` has been explicitly set.
  var hasTransitProviderEmail: Bool {return _storage._transitProviderEmail != nil}
  /// Clears the value of `transitProviderEmail`. Subsequent reads from it will return its default value.
  mutating func clearTransitProviderEmail() {_uniqueStorage()._transitProviderEmail = nil}

  /// The phone number for the transit provider.
  var transitProviderPhoneNumber: String {
    get {return _storage._transitProviderPhoneNumber ?? String()}
    set {_uniqueStorage()._transitProviderPhoneNumber = newValue}
  }
  /// Returns true if `transitProviderPhoneNumber` has been explicitly set.
  var hasTransitProviderPhoneNumber: Bool {return _storage._transitProviderPhoneNumber != nil}
  /// Clears the value of `transitProviderPhoneNumber`. Subsequent reads from it will return its default value.
  mutating func clearTransitProviderPhoneNumber() {_uniqueStorage()._transitProviderPhoneNumber = nil}

  /// The URL for the transit provider.
  var transitProviderWebsiteURL: String {
    get {return _storage._transitProviderWebsiteURL ?? String()}
    set {_uniqueStorage()._transitProviderWebsiteURL = newValue}
  }
  /// Returns true if `transitProviderWebsiteURL` has been explicitly set.
  var hasTransitProviderWebsiteURL: Bool {return _storage._transitProviderWebsiteURL != nil}
  /// Clears the value of `transitProviderWebsiteURL`. Subsequent reads from it will return its default value.
  mutating func clearTransitProviderWebsiteURL() {_uniqueStorage()._transitProviderWebsiteURL = nil}

  /// An ordered list of all upcoming pass information entries.
  var upcomingPassInformation: [PBUpcomingPassInformationEntry] {
    get {return _storage._upcomingPassInformation}
    set {_uniqueStorage()._upcomingPassInformation = newValue}
  }

  /// An array of featured actions.
  var featuredActions: [PBPassAction] {
    get {return _storage._featuredActions}
    set {_uniqueStorage()._featuredActions = newValue}
  }

  /// An SF Symbol to display as a logo image.
  var logoSymbolName: String {
    get {return _storage._logoSymbolName ?? String()}
    set {_uniqueStorage()._logoSymbolName = newValue}
  }
  /// Returns true if `logoSymbolName` has been explicitly set.
  var hasLogoSymbolName: Bool {return _storage._logoSymbolName != nil}
  /// Clears the value of `logoSymbolName`. Subsequent reads from it will return its default value.
  mutating func clearLogoSymbolName() {_uniqueStorage()._logoSymbolName = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "pass"

extension PBPass: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Pass"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{4}\u{2}serial_number\0\u{3}web_service_url\0\u{3}authentication_token\0\u{3}pass_type_identifier\0\u{3}team_identifier\0\u{3}organization_name\0\u{1}description\0\u{3}sharing_prohibited\0\u{2}\u{2}fields\0\u{3}associated_store_identifiers\0\u{3}auxiliary_store_identifiers\0\u{3}expiration_date\0\u{1}voided\0\u{1}barcodes\0\u{3}max_distance\0\u{3}relevant_date\0\u{3}relevant_dates\0\u{1}locations\0\u{1}beacons\0\u{3}background_color\0\u{3}foreground_color\0\u{3}label_color\0\u{3}strip_color\0\u{3}footer_background_color\0\u{3}suppress_header_darkening\0\u{3}use_automatic_colors\0\u{3}event_logo_text\0\u{3}logo_text\0\u{3}grouping_identifier\0\u{2}\u{2}nfc\0\u{3}preferred_style_schemes\0\u{1}semantics\0\u{3}app_launch_url\0\u{3}management_url\0\u{3}accessibility_url\0\u{3}add_on_url\0\u{3}bag_policy_url\0\u{3}merchandise_url\0\u{3}order_food_url\0\u{3}parking_information_url\0\u{3}purchase_parking_url\0\u{3}sell_url\0\u{3}transfer_url\0\u{3}transit_information_url\0\u{3}contact_venue_email\0\u{3}contact_venue_phone_number\0\u{3}contact_venue_website\0\u{3}directions_information_url\0\u{3}change_seat_url\0\u{3}entertainment_url\0\u{3}purchase_additional_baggage_url\0\u{3}purchase_lounge_access_url\0\u{3}purchase_wifi_url\0\u{3}upgrade_url\0\u{3}register_service_animal_url\0\u{3}report_lost_bag_url\0\u{3}request_wheelchair_url\0\u{3}transit_provider_email\0\u{3}transit_provider_phone_number\0\u{3}transit_provider_website_url\0\u{3}upcoming_pass_information\0\u{3}featured_actions\0\u{3}logo_symbol_name\0\u{c}\u{1}\u{1}\u{c} \u{1}")

  fileprivate class _StorageClass {
    var _serialNumber: String = String()
    var _webServiceURL: String? = nil
    var _authenticationToken: String? = nil
    var _passTypeIdentifier: String? = nil
    var _teamIdentifier: String? = nil
    var _organizationName: String? = nil
    var _description_p: String? = nil
    var _sharingProhibited: Bool? = nil
    var _fields: PBPassFields? = nil
    var _associatedStoreIdentifiers: [Int32] = []
    var _auxiliaryStoreIdentifiers: [Int32] = []
    var _expirationDate: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
    var _voided: Bool? = nil
    var _barcodes: [PBPassBarcode] = []
    var _maxDistance: Double? = nil
    var _relevantDate: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
    var _relevantDates: [PBPassRelevantDate] = []
    var _locations: [PBPassLocation] = []
    var _beacons: [PBPassBeacon] = []
    var _backgroundColor: PBPassColor? = nil
    var _foregroundColor: PBPassColor? = nil
    var _labelColor: PBPassColor? = nil
    var _stripColor: PBPassColor? = nil
    var _footerBackgroundColor: PBPassColor? = nil
    var _suppressHeaderDarkening: Bool? = nil
    var _useAutomaticColors: Bool? = nil
    var _eventLogoText: String? = nil
    var _logoText: String? = nil
    var _groupingIdentifier: String? = nil
    var _nfc: PBPassNFC? = nil
    var _preferredStyleSchemes: [String] = []
    var _semantics: PBPassSemantics? = nil
    var _appLaunchURL: String? = nil
    var _managementURL: String? = nil
    var _accessibilityURL: String? = nil
    var _addOnURL: String? = nil
    var _bagPolicyURL: String? = nil
    var _merchandiseURL: String? = nil
    var _orderFoodURL: String? = nil
    var _parkingInformationURL: String? = nil
    var _purchaseParkingURL: String? = nil
    var _sellURL: String? = nil
    var _transferURL: String? = nil
    var _transitInformationURL: String? = nil
    var _contactVenueEmail: String? = nil
    var _contactVenuePhoneNumber: String? = nil
    var _contactVenueWebsite: String? = nil
    var _directionsInformationURL: String? = nil
    var _changeSeatURL: String? = nil
    var _entertainmentURL: String? = nil
    var _purchaseAdditionalBaggageURL: String? = nil
    var _purchaseLoungeAccessURL: String? = nil
    var _purchaseWifiURL: String? = nil
    var _upgradeURL: String? = nil
    var _registerServiceAnimalURL: String? = nil
    var _reportLostBagURL: String? = nil
    var _requestWheelchairURL: String? = nil
    var _transitProviderEmail: String? = nil
    var _transitProviderPhoneNumber: String? = nil
    var _transitProviderWebsiteURL: String? = nil
    var _upcomingPassInformation: [PBUpcomingPassInformationEntry] = []
    var _featuredActions: [PBPassAction] = []
    var _logoSymbolName: String? = nil

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _serialNumber = source._serialNumber
      _webServiceURL = source._webServiceURL
      _authenticationToken = source._authenticationToken
      _passTypeIdentifier = source._passTypeIdentifier
      _teamIdentifier = source._teamIdentifier
      _organizationName = source._organizationName
      _description_p = source._description_p
      _sharingProhibited = source._sharingProhibited
      _fields = source._fields
      _associatedStoreIdentifiers = source._associatedStoreIdentifiers
      _auxiliaryStoreIdentifiers = source._auxiliaryStoreIdentifiers
      _expirationDate = source._expirationDate
      _voided = source._voided
      _barcodes = source._barcodes
      _maxDistance = source._maxDistance
      _relevantDate = source._relevantDate
      _relevantDates = source._relevantDates
      _locations = source._locations
      _beacons = source._beacons
      _backgroundColor = source._backgroundColor
      _foregroundColor = source._foregroundColor
      _labelColor = source._labelColor
      _stripColor = source._stripColor
      _footerBackgroundColor = source._footerBackgroundColor
      _suppressHeaderDarkening = source._suppressHeaderDarkening
      _useAutomaticColors = source._useAutomaticColors
      _eventLogoText = source._eventLogoText
      _logoText = source._logoText
      _groupingIdentifier = source._groupingIdentifier
      _nfc = source._nfc
      _preferredStyleSchemes = source._preferredStyleSchemes
      _semantics = source._semantics
      _appLaunchURL = source._appLaunchURL
      _managementURL = source._managementURL
      _accessibilityURL = source._accessibilityURL
      _addOnURL = source._addOnURL
      _bagPolicyURL = source._bagPolicyURL
      _merchandiseURL = source._merchandiseURL
      _orderFoodURL = source._orderFoodURL
      _parkingInformationURL = source._parkingInformationURL
      _purchaseParkingURL = source._purchaseParkingURL
      _sellURL = source._sellURL
      _transferURL = source._transferURL
      _transitInformationURL = source._transitInformationURL
      _contactVenueEmail = source._contactVenueEmail
      _contactVenuePhoneNumber = source._contactVenuePhoneNumber
      _contactVenueWebsite = source._contactVenueWebsite
      _directionsInformationURL = source._directionsInformationURL
      _changeSeatURL = source._changeSeatURL
      _entertainmentURL = source._entertainmentURL
      _purchaseAdditionalBaggageURL = source._purchaseAdditionalBaggageURL
      _purchaseLoungeAccessURL = source._purchaseLoungeAccessURL
      _purchaseWifiURL = source._purchaseWifiURL
      _upgradeURL = source._upgradeURL
      _registerServiceAnimalURL = source._registerServiceAnimalURL
      _reportLostBagURL = source._reportLostBagURL
      _requestWheelchairURL = source._requestWheelchairURL
      _transitProviderEmail = source._transitProviderEmail
      _transitProviderPhoneNumber = source._transitProviderPhoneNumber
      _transitProviderWebsiteURL = source._transitProviderWebsiteURL
      _upcomingPassInformation = source._upcomingPassInformation
      _featuredActions = source._featuredActions
      _logoSymbolName = source._logoSymbolName
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 2: try { try decoder.decodeSingularStringField(value: &_storage._serialNumber) }()
        case 3: try { try decoder.decodeSingularStringField(value: &_storage._webServiceURL) }()
        case 4: try { try decoder.decodeSingularStringField(value: &_storage._authenticationToken) }()
        case 5: try { try decoder.decodeSingularStringField(value: &_storage._passTypeIdentifier) }()
        case 6: try { try decoder.decodeSingularStringField(value: &_storage._teamIdentifier) }()
        case 7: try { try decoder.decodeSingularStringField(value: &_storage._organizationName) }()
        case 8: try { try decoder.decodeSingularStringField(value: &_storage._description_p) }()
        case 9: try { try decoder.decodeSingularBoolField(value: &_storage._sharingProhibited) }()
        case 11: try { try decoder.decodeSingularMessageField(value: &_storage._fields) }()
        case 12: try { try decoder.decodeRepeatedInt32Field(value: &_storage._associatedStoreIdentifiers) }()
        case 13: try { try decoder.decodeRepeatedInt32Field(value: &_storage._auxiliaryStoreIdentifiers) }()
        case 14: try { try decoder.decodeSingularMessageField(value: &_storage._expirationDate) }()
        case 15: try { try decoder.decodeSingularBoolField(value: &_storage._voided) }()
        case 16: try { try decoder.decodeRepeatedMessageField(value: &_storage._barcodes) }()
        case 17: try { try decoder.decodeSingularDoubleField(value: &_storage._maxDistance) }()
        case 18: try { try decoder.decodeSingularMessageField(value: &_storage._relevantDate) }()
        case 19: try { try decoder.decodeRepeatedMessageField(value: &_storage._relevantDates) }()
        case 20: try { try decoder.decodeRepeatedMessageField(value: &_storage._locations) }()
        case 21: try { try decoder.decodeRepeatedMessageField(value: &_storage._beacons) }()
        case 22: try { try decoder.decodeSingularMessageField(value: &_storage._backgroundColor) }()
        case 23: try { try decoder.decodeSingularMessageField(value: &_storage._foregroundColor) }()
        case 24: try { try decoder.decodeSingularMessageField(value: &_storage._labelColor) }()
        case 25: try { try decoder.decodeSingularMessageField(value: &_storage._stripColor) }()
        case 26: try { try decoder.decodeSingularMessageField(value: &_storage._footerBackgroundColor) }()
        case 27: try { try decoder.decodeSingularBoolField(value: &_storage._suppressHeaderDarkening) }()
        case 28: try { try decoder.decodeSingularBoolField(value: &_storage._useAutomaticColors) }()
        case 29: try { try decoder.decodeSingularStringField(value: &_storage._eventLogoText) }()
        case 30: try { try decoder.decodeSingularStringField(value: &_storage._logoText) }()
        case 31: try { try decoder.decodeSingularStringField(value: &_storage._groupingIdentifier) }()
        case 33: try { try decoder.decodeSingularMessageField(value: &_storage._nfc) }()
        case 34: try { try decoder.decodeRepeatedStringField(value: &_storage._preferredStyleSchemes) }()
        case 35: try { try decoder.decodeSingularMessageField(value: &_storage._semantics) }()
        case 36: try { try decoder.decodeSingularStringField(value: &_storage._appLaunchURL) }()
        case 37: try { try decoder.decodeSingularStringField(value: &_storage._managementURL) }()
        case 38: try { try decoder.decodeSingularStringField(value: &_storage._accessibilityURL) }()
        case 39: try { try decoder.decodeSingularStringField(value: &_storage._addOnURL) }()
        case 40: try { try decoder.decodeSingularStringField(value: &_storage._bagPolicyURL) }()
        case 41: try { try decoder.decodeSingularStringField(value: &_storage._merchandiseURL) }()
        case 42: try { try decoder.decodeSingularStringField(value: &_storage._orderFoodURL) }()
        case 43: try { try decoder.decodeSingularStringField(value: &_storage._parkingInformationURL) }()
        case 44: try { try decoder.decodeSingularStringField(value: &_storage._purchaseParkingURL) }()
        case 45: try { try decoder.decodeSingularStringField(value: &_storage._sellURL) }()
        case 46: try { try decoder.decodeSingularStringField(value: &_storage._transferURL) }()
        case 47: try { try decoder.decodeSingularStringField(value: &_storage._transitInformationURL) }()
        case 48: try { try decoder.decodeSingularStringField(value: &_storage._contactVenueEmail) }()
        case 49: try { try decoder.decodeSingularStringField(value: &_storage._contactVenuePhoneNumber) }()
        case 50: try { try decoder.decodeSingularStringField(value: &_storage._contactVenueWebsite) }()
        case 51: try { try decoder.decodeSingularStringField(value: &_storage._directionsInformationURL) }()
        case 52: try { try decoder.decodeSingularStringField(value: &_storage._changeSeatURL) }()
        case 53: try { try decoder.decodeSingularStringField(value: &_storage._entertainmentURL) }()
        case 54: try { try decoder.decodeSingularStringField(value: &_storage._purchaseAdditionalBaggageURL) }()
        case 55: try { try decoder.decodeSingularStringField(value: &_storage._purchaseLoungeAccessURL) }()
        case 56: try { try decoder.decodeSingularStringField(value: &_storage._purchaseWifiURL) }()
        case 57: try { try decoder.decodeSingularStringField(value: &_storage._upgradeURL) }()
        case 58: try { try decoder.decodeSingularStringField(value: &_storage._registerServiceAnimalURL) }()
        case 59: try { try decoder.decodeSingularStringField(value: &_storage._reportLostBagURL) }()
        case 60: try { try decoder.decodeSingularStringField(value: &_storage._requestWheelchairURL) }()
        case 61: try { try decoder.decodeSingularStringField(value: &_storage._transitProviderEmail) }()
        case 62: try { try decoder.decodeSingularStringField(value: &_storage._transitProviderPhoneNumber) }()
        case 63: try { try decoder.decodeSingularStringField(value: &_storage._transitProviderWebsiteURL) }()
        case 64: try { try decoder.decodeRepeatedMessageField(value: &_storage._upcomingPassInformation) }()
        case 65: try { try decoder.decodeRepeatedMessageField(value: &_storage._featuredActions) }()
        case 66: try { try decoder.decodeSingularStringField(value: &_storage._logoSymbolName) }()
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if !_storage._serialNumber.isEmpty {
        try visitor.visitSingularStringField(value: _storage._serialNumber, fieldNumber: 2)
      }
      try { if let v = _storage._webServiceURL {
        try visitor.visitSingularStringField(value: v, fieldNumber: 3)
      } }()
      try { if let v = _storage._authenticationToken {
        try visitor.visitSingularStringField(value: v, fieldNumber: 4)
      } }()
      try { if let v = _storage._passTypeIdentifier {
        try visitor.visitSingularStringField(value: v, fieldNumber: 5)
      } }()
      try { if let v = _storage._teamIdentifier {
        try visitor.visitSingularStringField(value: v, fieldNumber: 6)
      } }()
      try { if let v = _storage._organizationName {
        try visitor.visitSingularStringField(value: v, fieldNumber: 7)
      } }()
      try { if let v = _storage._description_p {
        try visitor.visitSingularStringField(value: v, fieldNumber: 8)
      } }()
      try { if let v = _storage._sharingProhibited {
        try visitor.visitSingularBoolField(value: v, fieldNumber: 9)
      } }()
      try { if let v = _storage._fields {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 11)
      } }()
      if !_storage._associatedStoreIdentifiers.isEmpty {
        try visitor.visitPackedInt32Field(value: _storage._associatedStoreIdentifiers, fieldNumber: 12)
      }
      if !_storage._auxiliaryStoreIdentifiers.isEmpty {
        try visitor.visitPackedInt32Field(value: _storage._auxiliaryStoreIdentifiers, fieldNumber: 13)
      }
      try { if let v = _storage._expirationDate {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 14)
      } }()
      try { if let v = _storage._voided {
        try visitor.visitSingularBoolField(value: v, fieldNumber: 15)
      } }()
      if !_storage._barcodes.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._barcodes, fieldNumber: 16)
      }
      try { if let v = _storage._maxDistance {
        try visitor.visitSingularDoubleField(value: v, fieldNumber: 17)
      } }()
      try { if let v = _storage._relevantDate {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 18)
      } }()
      if !_storage._relevantDates.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._relevantDates, fieldNumber: 19)
      }
      if !_storage._locations.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._locations, fieldNumber: 20)
      }
      if !_storage._beacons.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._beacons, fieldNumber: 21)
      }
      try { if let v = _storage._backgroundColor {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 22)
      } }()
      try { if let v = _storage._foregroundColor {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 23)
      } }()
      try { if let v = _storage._labelColor {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 24)
      } }()
      try { if let v = _storage._stripColor {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 25)
      } }()
      try { if let v = _storage._footerBackgroundColor {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 26)
      } }()
      try { if let v = _storage._suppressHeaderDarkening {
        try visitor.visitSingularBoolField(value: v, fieldNumber: 27)
      } }()
      try { if let v = _storage._useAutomaticColors {
        try visitor.visitSingularBoolField(value: v, fieldNumber: 28)
      } }()
      try { if let v = _storage._eventLogoText {
        try visitor.visitSingularStringField(value: v, fieldNumber: 29)
      } }()
      try { if let v = _storage._logoText {
        try visitor.visitSingularStringField(value: v, fieldNumber: 30)
      } }()
      try { if let v = _storage._groupingIdentifier {
        try visitor.visitSingularStringField(value: v, fieldNumber: 31)
      } }()
      try { if let v = _storage._nfc {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 33)
      } }()
      if !_storage._preferredStyleSchemes.isEmpty {
        try visitor.visitRepeatedStringField(value: _storage._preferredStyleSchemes, fieldNumber: 34)
      }
      try { if let v = _storage._semantics {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 35)
      } }()
      try { if let v = _storage._appLaunchURL {
        try visitor.visitSingularStringField(value: v, fieldNumber: 36)
      } }()
      try { if let v = _storage._managementURL {
        try visitor.visitSingularStringField(value: v, fieldNumber: 37)
      } }()
      try { if let v = _storage._accessibilityURL {
        try visitor.visitSingularStringField(value: v, fieldNumber: 38)
      } }()
      try { if let v = _storage._addOnURL {
        try visitor.visitSingularStringField(value: v, fieldNumber: 39)
      } }()
      try { if let v = _storage._bagPolicyURL {
        try visitor.visitSingularStringField(value: v, fieldNumber: 40)
      } }()
      try { if let v = _storage._merchandiseURL {
        try visitor.visitSingularStringField(value: v, fieldNumber: 41)
      } }()
      try { if let v = _storage._orderFoodURL {
        try visitor.visitSingularStringField(value: v, fieldNumber: 42)
      } }()
      try { if let v = _storage._parkingInformationURL {
        try visitor.visitSingularStringField(value: v, fieldNumber: 43)
      } }()
      try { if let v = _storage._purchaseParkingURL {
        try visitor.visitSingularStringField(value: v, fieldNumber: 44)
      } }()
      try { if let v = _storage._sellURL {
        try visitor.visitSingularStringField(value: v, fieldNumber: 45)
      } }()
      try { if let v = _storage._transferURL {
        try visitor.visitSingularStringField(value: v, fieldNumber: 46)
      } }()
      try { if let v = _storage._transitInformationURL {
        try visitor.visitSingularStringField(value: v, fieldNumber: 47)
      } }()
      try { if let v = _storage._contactVenueEmail {
        try visitor.visitSingularStringField(value: v, fieldNumber: 48)
      } }()
      try { if let v = _storage._contactVenuePhoneNumber {
        try visitor.visitSingularStringField(value: v, fieldNumber: 49)
      } }()
      try { if let v = _storage._contactVenueWebsite {
        try visitor.visitSingularStringField(value: v, fieldNumber: 50)
      } }()
      try { if let v = _storage._directionsInformationURL {
        try visitor.visitSingularStringField(value: v, fieldNumber: 51)
      } }()
      try { if let v = _storage._changeSeatURL {
        try visitor.visitSingularStringField(value: v, fieldNumber: 52)
      } }()
      try { if let v = _storage._entertainmentURL {
        try visitor.visitSingularStringField(value: v, fieldNumber: 53)
      } }()
      try { if let v = _storage._purchaseAdditionalBaggageURL {
        try visitor.visitSingularStringField(value: v, fieldNumber: 54)
      } }()
      try { if let v = _storage._purchaseLoungeAccessURL {
        try visitor.visitSingularStringField(value: v, fieldNumber: 55)
      } }()
      try { if let v = _storage._purchaseWifiURL {
        try visitor.visitSingularStringField(value: v, fieldNumber: 56)
      } }()
      try { if let v = _storage._upgradeURL {
        try visitor.visitSingularStringField(value: v, fieldNumber: 57)
      } }()
      try { if let v = _storage._registerServiceAnimalURL {
        try visitor.visitSingularStringField(value: v, fieldNumber: 58)
      } }()
      try { if let v = _storage._reportLostBagURL {
        try visitor.visitSingularStringField(value: v, fieldNumber: 59)
      } }()
      try { if let v = _storage._requestWheelchairURL {
        try visitor.visitSingularStringField(value: v, fieldNumber: 60)
      } }()
      try { if let v = _storage._transitProviderEmail {
        try visitor.visitSingularStringField(value: v, fieldNumber: 61)
      } }()
      try { if let v = _storage._transitProviderPhoneNumber {
        try visitor.visitSingularStringField(value: v, fieldNumber: 62)
      } }()
      try { if let v = _storage._transitProviderWebsiteURL {
        try visitor.visitSingularStringField(value: v, fieldNumber: 63)
      } }()
      if !_storage._upcomingPassInformation.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._upcomingPassInformation, fieldNumber: 64)
      }
      if !_storage._featuredActions.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._featuredActions, fieldNumber: 65)
      }
      try { if let v = _storage._logoSymbolName {
        try visitor.visitSingularStringField(value: v, fieldNumber: 66)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: PBPass, rhs: PBPass) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._serialNumber != rhs_storage._serialNumber {return false}
        if _storage._webServiceURL != rhs_storage._webServiceURL {return false}
        if _storage._authenticationToken != rhs_storage._authenticationToken {return false}
        if _storage._passTypeIdentifier != rhs_storage._passTypeIdentifier {return false}
        if _storage._teamIdentifier != rhs_storage._teamIdentifier {return false}
        if _storage._organizationName != rhs_storage._organizationName {return false}
        if _storage._description_p != rhs_storage._description_p {return false}
        if _storage._sharingProhibited != rhs_storage._sharingProhibited {return false}
        if _storage._fields != rhs_storage._fields {return false}
        if _storage._associatedStoreIdentifiers != rhs_storage._associatedStoreIdentifiers {return false}
        if _storage._auxiliaryStoreIdentifiers != rhs_storage._auxiliaryStoreIdentifiers {return false}
        if _storage._expirationDate != rhs_storage._expirationDate {return false}
        if _storage._voided != rhs_storage._voided {return false}
        if _storage._barcodes != rhs_storage._barcodes {return false}
        if _storage._maxDistance != rhs_storage._maxDistance {return false}
        if _storage._relevantDate != rhs_storage._relevantDate {return false}
        if _storage._relevantDates != rhs_storage._relevantDates {return false}
        if _storage._locations != rhs_storage._locations {return false}
        if _storage._beacons != rhs_storage._beacons {return false}
        if _storage._backgroundColor != rhs_storage._backgroundColor {return false}
        if _storage._foregroundColor != rhs_storage._foregroundColor {return false}
        if _storage._labelColor != rhs_storage._labelColor {return false}
        if _storage._stripColor != rhs_storage._stripColor {return false}
        if _storage._footerBackgroundColor != rhs_storage._footerBackgroundColor {return false}
        if _storage._suppressHeaderDarkening != rhs_storage._suppressHeaderDarkening {return false}
        if _storage._useAutomaticColors != rhs_storage._useAutomaticColors {return false}
        if _storage._eventLogoText != rhs_storage._eventLogoText {return false}
        if _storage._logoText != rhs_storage._logoText {return false}
        if _storage._groupingIdentifier != rhs_storage._groupingIdentifier {return false}
        if _storage._nfc != rhs_storage._nfc {return false}
        if _storage._preferredStyleSchemes != rhs_storage._preferredStyleSchemes {return false}
        if _storage._semantics != rhs_storage._semantics {return false}
        if _storage._appLaunchURL != rhs_storage._appLaunchURL {return false}
        if _storage._managementURL != rhs_storage._managementURL {return false}
        if _storage._accessibilityURL != rhs_storage._accessibilityURL {return false}
        if _storage._addOnURL != rhs_storage._addOnURL {return false}
        if _storage._bagPolicyURL != rhs_storage._bagPolicyURL {return false}
        if _storage._merchandiseURL != rhs_storage._merchandiseURL {return false}
        if _storage._orderFoodURL != rhs_storage._orderFoodURL {return false}
        if _storage._parkingInformationURL != rhs_storage._parkingInformationURL {return false}
        if _storage._purchaseParkingURL != rhs_storage._purchaseParkingURL {return false}
        if _storage._sellURL != rhs_storage._sellURL {return false}
        if _storage._transferURL != rhs_storage._transferURL {return false}
        if _storage._transitInformationURL != rhs_storage._transitInformationURL {return false}
        if _storage._contactVenueEmail != rhs_storage._contactVenueEmail {return false}
        if _storage._contactVenuePhoneNumber != rhs_storage._contactVenuePhoneNumber {return false}
        if _storage._contactVenueWebsite != rhs_storage._contactVenueWebsite {return false}
        if _storage._directionsInformationURL != rhs_storage._directionsInformationURL {return false}
        if _storage._changeSeatURL != rhs_storage._changeSeatURL {return false}
        if _storage._entertainmentURL != rhs_storage._entertainmentURL {return false}
        if _storage._purchaseAdditionalBaggageURL != rhs_storage._purchaseAdditionalBaggageURL {return false}
        if _storage._purchaseLoungeAccessURL != rhs_storage._purchaseLoungeAccessURL {return false}
        if _storage._purchaseWifiURL != rhs_storage._purchaseWifiURL {return false}
        if _storage._upgradeURL != rhs_storage._upgradeURL {return false}
        if _storage._registerServiceAnimalURL != rhs_storage._registerServiceAnimalURL {return false}
        if _storage._reportLostBagURL != rhs_storage._reportLostBagURL {return false}
        if _storage._requestWheelchairURL != rhs_storage._requestWheelchairURL {return false}
        if _storage._transitProviderEmail != rhs_storage._transitProviderEmail {return false}
        if _storage._transitProviderPhoneNumber != rhs_storage._transitProviderPhoneNumber {return false}
        if _storage._transitProviderWebsiteURL != rhs_storage._transitProviderWebsiteURL {return false}
        if _storage._upcomingPassInformation != rhs_storage._upcomingPassInformation {return false}
        if _storage._featuredActions != rhs_storage._featuredActions {return false}
        if _storage._logoSymbolName != rhs_storage._logoSymbolName {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
