// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: PassDataDetectorType.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Data Detector Type Enum
enum PBPassDataDetectorType: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case dataDetectorTypeUnspecified // = 0
  case dataDetectorTypePhoneNumber // = 1
  case dataDetectorTypeLink // = 2
  case dataDetectorTypeAddress // = 3
  case dataDetectorTypeCalendarEvent // = 4
  case UNRECOGNIZED(Int)

  init() {
    self = .dataDetectorTypeUnspecified
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .dataDetectorTypeUnspecified
    case 1: self = .dataDetectorTypePhoneNumber
    case 2: self = .dataDetectorTypeLink
    case 3: self = .dataDetectorTypeAddress
    case 4: self = .dataDetectorTypeCalendarEvent
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .dataDetectorTypeUnspecified: return 0
    case .dataDetectorTypePhoneNumber: return 1
    case .dataDetectorTypeLink: return 2
    case .dataDetectorTypeAddress: return 3
    case .dataDetectorTypeCalendarEvent: return 4
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [PBPassDataDetectorType] = [
    .dataDetectorTypeUnspecified,
    .dataDetectorTypePhoneNumber,
    .dataDetectorTypeLink,
    .dataDetectorTypeAddress,
    .dataDetectorTypeCalendarEvent,
  ]

}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension PBPassDataDetectorType: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0DATA_DETECTOR_TYPE_UNSPECIFIED\0\u{1}DATA_DETECTOR_TYPE_PHONE_NUMBER\0\u{1}DATA_DETECTOR_TYPE_LINK\0\u{1}DATA_DETECTOR_TYPE_ADDRESS\0\u{1}DATA_DETECTOR_TYPE_CALENDAR_EVENT\0")
}
