// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: PassFields.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// A message that represents the groups of fields that display information on the front and back of a pass.
struct PBPassFields: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Customize fields in a pkpasstemplate.
  /// If a corresponding field list (e.g. header_fields) is explicitly set, any customizations for fields will be
  /// discarded in favor of the explicit definition.
  var fieldCustomization: PBPassFieldsTemplateCustomization {
    get {return _fieldCustomization ?? PBPassFieldsTemplateCustomization()}
    set {_fieldCustomization = newValue}
  }
  /// Returns true if `fieldCustomization` has been explicitly set.
  var hasFieldCustomization: Bool {return self._fieldCustomization != nil}
  /// Clears the value of `fieldCustomization`. Subsequent reads from it will return its default value.
  mutating func clearFieldCustomization() {self._fieldCustomization = nil}

  /// An object that represents the fields that display information at the top of a pass.
  var headerFields: PBPassFieldsList {
    get {return _headerFields ?? PBPassFieldsList()}
    set {_headerFields = newValue}
  }
  /// Returns true if `headerFields` has been explicitly set.
  var hasHeaderFields: Bool {return self._headerFields != nil}
  /// Clears the value of `headerFields`. Subsequent reads from it will return its default value.
  mutating func clearHeaderFields() {self._headerFields = nil}

  /// An object that represents the fields that display the most important information on a pass.
  var primaryFields: PBPassFieldsList {
    get {return _primaryFields ?? PBPassFieldsList()}
    set {_primaryFields = newValue}
  }
  /// Returns true if `primaryFields` has been explicitly set.
  var hasPrimaryFields: Bool {return self._primaryFields != nil}
  /// Clears the value of `primaryFields`. Subsequent reads from it will return its default value.
  mutating func clearPrimaryFields() {self._primaryFields = nil}

  /// An object that represents the fields that display supporting information on the front of a pass.
  var secondaryFields: PBPassFieldsList {
    get {return _secondaryFields ?? PBPassFieldsList()}
    set {_secondaryFields = newValue}
  }
  /// Returns true if `secondaryFields` has been explicitly set.
  var hasSecondaryFields: Bool {return self._secondaryFields != nil}
  /// Clears the value of `secondaryFields`. Subsequent reads from it will return its default value.
  mutating func clearSecondaryFields() {self._secondaryFields = nil}

  /// An object that represents the fields that display additional information on the front of a pass.
  var auxiliaryFields: PBPassFieldsList {
    get {return _auxiliaryFields ?? PBPassFieldsList()}
    set {_auxiliaryFields = newValue}
  }
  /// Returns true if `auxiliaryFields` has been explicitly set.
  var hasAuxiliaryFields: Bool {return self._auxiliaryFields != nil}
  /// Clears the value of `auxiliaryFields`. Subsequent reads from it will return its default value.
  mutating func clearAuxiliaryFields() {self._auxiliaryFields = nil}

  /// An object that represents the fields that display information on the back of a pass.
  var backFields: PBPassFieldsList {
    get {return _backFields ?? PBPassFieldsList()}
    set {_backFields = newValue}
  }
  /// Returns true if `backFields` has been explicitly set.
  var hasBackFields: Bool {return self._backFields != nil}
  /// Clears the value of `backFields`. Subsequent reads from it will return its default value.
  mutating func clearBackFields() {self._backFields = nil}

  /// An object that represents fields that display in the Additional Info section below a pass.
  var additionalInfoFields: PBPassFieldsList {
    get {return _additionalInfoFields ?? PBPassFieldsList()}
    set {_additionalInfoFields = newValue}
  }
  /// Returns true if `additionalInfoFields` has been explicitly set.
  var hasAdditionalInfoFields: Bool {return self._additionalInfoFields != nil}
  /// Clears the value of `additionalInfoFields`. Subsequent reads from it will return its default value.
  mutating func clearAdditionalInfoFields() {self._additionalInfoFields = nil}

  /// (Required when Boarding Pass) The type of transit for a boarding pass. This key is invalid for other types
  /// of passes. The system may use the value to display more information, such as showing an airplane icon for
  /// the pass on watchOS when the value is set to `PKTransitTypeAir`.
  var transitType: PBPassTransitType {
    get {return _transitType ?? .transitTypeUnspecified}
    set {_transitType = newValue}
  }
  /// Returns true if `transitType` has been explicitly set.
  var hasTransitType: Bool {return self._transitType != nil}
  /// Clears the value of `transitType`. Subsequent reads from it will return its default value.
  mutating func clearTransitType() {self._transitType = nil}

  /// An object that represents fields that display in the footer of a pass face.
  var footerFields: PBPassFieldsList {
    get {return _footerFields ?? PBPassFieldsList()}
    set {_footerFields = newValue}
  }
  /// Returns true if `footerFields` has been explicitly set.
  var hasFooterFields: Bool {return self._footerFields != nil}
  /// Clears the value of `footerFields`. Subsequent reads from it will return its default value.
  mutating func clearFooterFields() {self._footerFields = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _fieldCustomization: PBPassFieldsTemplateCustomization? = nil
  fileprivate var _headerFields: PBPassFieldsList? = nil
  fileprivate var _primaryFields: PBPassFieldsList? = nil
  fileprivate var _secondaryFields: PBPassFieldsList? = nil
  fileprivate var _auxiliaryFields: PBPassFieldsList? = nil
  fileprivate var _backFields: PBPassFieldsList? = nil
  fileprivate var _additionalInfoFields: PBPassFieldsList? = nil
  fileprivate var _transitType: PBPassTransitType? = nil
  fileprivate var _footerFields: PBPassFieldsList? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "pass"

extension PBPassFields: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".PassFields"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}field_customization\0\u{3}header_fields\0\u{3}primary_fields\0\u{3}secondary_fields\0\u{3}auxiliary_fields\0\u{3}back_fields\0\u{3}additional_info_fields\0\u{3}transit_type\0\u{3}footer_fields\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._fieldCustomization) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._headerFields) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._primaryFields) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._secondaryFields) }()
      case 5: try { try decoder.decodeSingularMessageField(value: &self._auxiliaryFields) }()
      case 6: try { try decoder.decodeSingularMessageField(value: &self._backFields) }()
      case 7: try { try decoder.decodeSingularMessageField(value: &self._additionalInfoFields) }()
      case 8: try { try decoder.decodeSingularEnumField(value: &self._transitType) }()
      case 9: try { try decoder.decodeSingularMessageField(value: &self._footerFields) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._fieldCustomization {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._headerFields {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._primaryFields {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._secondaryFields {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._auxiliaryFields {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._backFields {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._additionalInfoFields {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
    } }()
    try { if let v = self._transitType {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 8)
    } }()
    try { if let v = self._footerFields {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: PBPassFields, rhs: PBPassFields) -> Bool {
    if lhs._fieldCustomization != rhs._fieldCustomization {return false}
    if lhs._headerFields != rhs._headerFields {return false}
    if lhs._primaryFields != rhs._primaryFields {return false}
    if lhs._secondaryFields != rhs._secondaryFields {return false}
    if lhs._auxiliaryFields != rhs._auxiliaryFields {return false}
    if lhs._backFields != rhs._backFields {return false}
    if lhs._additionalInfoFields != rhs._additionalInfoFields {return false}
    if lhs._transitType != rhs._transitType {return false}
    if lhs._footerFields != rhs._footerFields {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
