// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: PassBarcode.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Barcode Format Enum
enum PBPassBarcodeFormat: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case barcodeFormatUnspecified // = 0
  case barcodeFormatQr // = 1
  case barcodeFormatPdf417 // = 2
  case barcodeFormatAztec // = 3
  case barcodeFormatCode128 // = 4
  case barcodeFormatEan13 // = 5
  case barcodeFormatCodabar // = 6
  case barcodeFormatCode39 // = 7
  case barcodeFormatI2Of5 // = 8
  case UNRECOGNIZED(Int)

  init() {
    self = .barcodeFormatUnspecified
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .barcodeFormatUnspecified
    case 1: self = .barcodeFormatQr
    case 2: self = .barcodeFormatPdf417
    case 3: self = .barcodeFormatAztec
    case 4: self = .barcodeFormatCode128
    case 5: self = .barcodeFormatEan13
    case 6: self = .barcodeFormatCodabar
    case 7: self = .barcodeFormatCode39
    case 8: self = .barcodeFormatI2Of5
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .barcodeFormatUnspecified: return 0
    case .barcodeFormatQr: return 1
    case .barcodeFormatPdf417: return 2
    case .barcodeFormatAztec: return 3
    case .barcodeFormatCode128: return 4
    case .barcodeFormatEan13: return 5
    case .barcodeFormatCodabar: return 6
    case .barcodeFormatCode39: return 7
    case .barcodeFormatI2Of5: return 8
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [PBPassBarcodeFormat] = [
    .barcodeFormatUnspecified,
    .barcodeFormatQr,
    .barcodeFormatPdf417,
    .barcodeFormatAztec,
    .barcodeFormatCode128,
    .barcodeFormatEan13,
    .barcodeFormatCodabar,
    .barcodeFormatCode39,
    .barcodeFormatI2Of5,
  ]

}

/// A message that represents a barcode on a pass.
struct PBPassBarcode: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// (Required) The format of the barcode.
  /// The barcode format PKBarcodeFormatCode128 isn’t supported for watchOS.
  var format: PBPassBarcodeFormat = .barcodeFormatUnspecified

  /// (Required) The message or payload to display as a barcode.
  var message: String = String()

  /// (Required) The IANA character set name of the text encoding to use to convert message from a string
  /// representation to a data representation that the system renders as a barcode, such as “iso-8859-1”.
  var messageEncoding: String = String()

  /// The text to display near the barcode. For example, a human-readable version of the barcode data in case
  /// the barcode doesn’t scan.
  /// The alternative text isn’t displayed for watchOS.
  var altText: String {
    get {return _altText ?? String()}
    set {_altText = newValue}
  }
  /// Returns true if `altText` has been explicitly set.
  var hasAltText: Bool {return self._altText != nil}
  /// Clears the value of `altText`. Subsequent reads from it will return its default value.
  mutating func clearAltText() {self._altText = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _altText: String? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "pass"

extension PBPassBarcodeFormat: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0BARCODE_FORMAT_UNSPECIFIED\0\u{1}BARCODE_FORMAT_QR\0\u{1}BARCODE_FORMAT_PDF417\0\u{1}BARCODE_FORMAT_AZTEC\0\u{1}BARCODE_FORMAT_CODE128\0\u{1}BARCODE_FORMAT_EAN13\0\u{1}BARCODE_FORMAT_CODABAR\0\u{1}BARCODE_FORMAT_CODE39\0\u{1}BARCODE_FORMAT_I2OF5\0")
}

extension PBPassBarcode: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".PassBarcode"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}format\0\u{1}message\0\u{3}message_encoding\0\u{3}alt_text\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.format) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.message) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.messageEncoding) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self._altText) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.format != .barcodeFormatUnspecified {
      try visitor.visitSingularEnumField(value: self.format, fieldNumber: 1)
    }
    if !self.message.isEmpty {
      try visitor.visitSingularStringField(value: self.message, fieldNumber: 2)
    }
    if !self.messageEncoding.isEmpty {
      try visitor.visitSingularStringField(value: self.messageEncoding, fieldNumber: 3)
    }
    try { if let v = self._altText {
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: PBPassBarcode, rhs: PBPassBarcode) -> Bool {
    if lhs.format != rhs.format {return false}
    if lhs.message != rhs.message {return false}
    if lhs.messageEncoding != rhs.messageEncoding {return false}
    if lhs._altText != rhs._altText {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
