// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: PassNumberFormat.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Number Format Enum
enum PBPassNumberFormat: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case numberFormatUnspecified // = 0
  case numberFormatDecimal // = 1
  case numberFormatPercent // = 2
  case numberFormatScientific // = 3
  case numberFormatSpellOut // = 4
  case UNRECOGNIZED(Int)

  init() {
    self = .numberFormatUnspecified
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .numberFormatUnspecified
    case 1: self = .numberFormatDecimal
    case 2: self = .numberFormatPercent
    case 3: self = .numberFormatScientific
    case 4: self = .numberFormatSpellOut
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .numberFormatUnspecified: return 0
    case .numberFormatDecimal: return 1
    case .numberFormatPercent: return 2
    case .numberFormatScientific: return 3
    case .numberFormatSpellOut: return 4
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [PBPassNumberFormat] = [
    .numberFormatUnspecified,
    .numberFormatDecimal,
    .numberFormatPercent,
    .numberFormatScientific,
    .numberFormatSpellOut,
  ]

}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension PBPassNumberFormat: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0NUMBER_FORMAT_UNSPECIFIED\0\u{1}NUMBER_FORMAT_DECIMAL\0\u{1}NUMBER_FORMAT_PERCENT\0\u{1}NUMBER_FORMAT_SCIENTIFIC\0\u{1}NUMBER_FORMAT_SPELL_OUT\0")
}
