// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: PassFieldContent.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// A message that represents the information to display in a field on a pass.
struct PBPassFieldContent: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// (Required) A unique key that identifies a field in the pass; for example, “departure-gate”.
  var key: String = String()

  /// (Required) The value to use for the field; for example, 42. A date or time value needs to include a
  /// time zone.
  var value: PBPassFieldValue {
    get {return _value ?? PBPassFieldValue()}
    set {_value = newValue}
  }
  /// Returns true if `value` has been explicitly set.
  var hasValue: Bool {return self._value != nil}
  /// Clears the value of `value`. Subsequent reads from it will return its default value.
  mutating func clearValue() {self._value = nil}

  /// The text for a field label.
  var label: String {
    get {return _label ?? String()}
    set {_label = newValue}
  }
  /// Returns true if `label` has been explicitly set.
  var hasLabel: Bool {return self._label != nil}
  /// Clears the value of `label`. Subsequent reads from it will return its default value.
  mutating func clearLabel() {self._label = nil}

  /// The value of the field, including HTML markup for links. The only supported tag is the <a> tag and its href
  /// attribute. The value of this key overrides that of the value key.
  /// For example, the following is a key-value pair that specifies a link with the text “Edit my profile”:
  /// ”attributedValue”: “<a href=’http://example.com/customers/123’>Edit my profile</a>”
  /// The attributed value isn’t used for watchOS; use the value field instead.
  var attributedValue: String {
    get {return _attributedValue ?? String()}
    set {_attributedValue = newValue}
  }
  /// Returns true if `attributedValue` has been explicitly set.
  var hasAttributedValue: Bool {return self._attributedValue != nil}
  /// Clears the value of `attributedValue`. Subsequent reads from it will return its default value.
  mutating func clearAttributedValue() {self._attributedValue = nil}

  /// A format string for the alert text to display when the pass updates. The format string needs to contain
  /// the escape %@, which the field’s new value replaces. For example, Gate changed to %@.
  /// You need to provide a value for the system to show a change notification.
  /// This field isn’t used for watchOS.
  var changeMessage: String {
    get {return _changeMessage ?? String()}
    set {_changeMessage = newValue}
  }
  /// Returns true if `changeMessage` has been explicitly set.
  var hasChangeMessage: Bool {return self._changeMessage != nil}
  /// Clears the value of `changeMessage`. Subsequent reads from it will return its default value.
  mutating func clearChangeMessage() {self._changeMessage = nil}

  /// The data detectors to apply to the value of a field on the back of the pass. The default is to apply all
  /// data detectors. To use no data detectors, specify an empty array. You don’t use data detectors for fields on
  /// the front of the pass.
  var dataDetectorTypes: [PBPassDataDetectorType] = []

  /// The alignment for the content of a field. The default is natural alignment, which aligns the text based on
  /// its script direction. This key is invalid for primary and back fields.
  var textAlignment: PBPassTextAlignment {
    get {return _textAlignment ?? .textAlignmentUnspecified}
    set {_textAlignment = newValue}
  }
  /// Returns true if `textAlignment` has been explicitly set.
  var hasTextAlignment: Bool {return self._textAlignment != nil}
  /// Clears the value of `textAlignment`. Subsequent reads from it will return its default value.
  mutating func clearTextAlignment() {self._textAlignment = nil}

  /// The style of the date to display in the field.
  var dateStyle: PBPassDateTimeFormat {
    get {return _dateStyle ?? .dateTimeFormatUnspecified}
    set {_dateStyle = newValue}
  }
  /// Returns true if `dateStyle` has been explicitly set.
  var hasDateStyle: Bool {return self._dateStyle != nil}
  /// Clears the value of `dateStyle`. Subsequent reads from it will return its default value.
  mutating func clearDateStyle() {self._dateStyle = nil}

  /// The style of the time displayed in the field.
  var timeStyle: PBPassDateTimeFormat {
    get {return _timeStyle ?? .dateTimeFormatUnspecified}
    set {_timeStyle = newValue}
  }
  /// Returns true if `timeStyle` has been explicitly set.
  var hasTimeStyle: Bool {return self._timeStyle != nil}
  /// Clears the value of `timeStyle`. Subsequent reads from it will return its default value.
  mutating func clearTimeStyle() {self._timeStyle = nil}

  /// A Boolean value that controls the time zone for the time and date to display in the field. The default
  /// value is false, which displays the time and date using the current device’s time zone. Otherwise, the
  /// time and date appear in the time zone associated with the date and time of value.
  /// This key doesn’t affect the pass relevance calculation.
  var ignoresTimeZone: Bool {
    get {return _ignoresTimeZone ?? false}
    set {_ignoresTimeZone = newValue}
  }
  /// Returns true if `ignoresTimeZone` has been explicitly set.
  var hasIgnoresTimeZone: Bool {return self._ignoresTimeZone != nil}
  /// Clears the value of `ignoresTimeZone`. Subsequent reads from it will return its default value.
  mutating func clearIgnoresTimeZone() {self._ignoresTimeZone = nil}

  /// A Boolean value that controls whether the date appears as a relative date. The default value is false,
  /// which displays the date as an absolute date.
  /// This key doesn’t affect the pass relevance calculation.
  var isRelative: Bool {
    get {return _isRelative ?? false}
    set {_isRelative = newValue}
  }
  /// Returns true if `isRelative` has been explicitly set.
  var hasIsRelative: Bool {return self._isRelative != nil}
  /// Clears the value of `isRelative`. Subsequent reads from it will return its default value.
  mutating func clearIsRelative() {self._isRelative = nil}

  /// The style of the number to display in the field. Formatter styles have the same meaning as the formats with
  /// corresponding names in NumberFormatter.Style.
  var numberStyle: PBPassNumberFormat {
    get {return _numberStyle ?? .numberFormatUnspecified}
    set {_numberStyle = newValue}
  }
  /// Returns true if `numberStyle` has been explicitly set.
  var hasNumberStyle: Bool {return self._numberStyle != nil}
  /// Clears the value of `numberStyle`. Subsequent reads from it will return its default value.
  mutating func clearNumberStyle() {self._numberStyle = nil}

  /// The currency code to use for the value of the field.
  var currencyCode: String {
    get {return _currencyCode ?? String()}
    set {_currencyCode = newValue}
  }
  /// Returns true if `currencyCode` has been explicitly set.
  var hasCurrencyCode: Bool {return self._currencyCode != nil}
  /// Clears the value of `currencyCode`. Subsequent reads from it will return its default value.
  mutating func clearCurrencyCode() {self._currencyCode = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _value: PBPassFieldValue? = nil
  fileprivate var _label: String? = nil
  fileprivate var _attributedValue: String? = nil
  fileprivate var _changeMessage: String? = nil
  fileprivate var _textAlignment: PBPassTextAlignment? = nil
  fileprivate var _dateStyle: PBPassDateTimeFormat? = nil
  fileprivate var _timeStyle: PBPassDateTimeFormat? = nil
  fileprivate var _ignoresTimeZone: Bool? = nil
  fileprivate var _isRelative: Bool? = nil
  fileprivate var _numberStyle: PBPassNumberFormat? = nil
  fileprivate var _currencyCode: String? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "pass"

extension PBPassFieldContent: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".PassFieldContent"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}key\0\u{1}value\0\u{1}label\0\u{3}attributed_value\0\u{3}change_message\0\u{3}data_detector_types\0\u{3}text_alignment\0\u{3}date_style\0\u{3}time_style\0\u{3}ignores_time_zone\0\u{3}is_relative\0\u{3}number_style\0\u{3}currency_code\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.key) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._value) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._label) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self._attributedValue) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self._changeMessage) }()
      case 6: try { try decoder.decodeRepeatedEnumField(value: &self.dataDetectorTypes) }()
      case 7: try { try decoder.decodeSingularEnumField(value: &self._textAlignment) }()
      case 8: try { try decoder.decodeSingularEnumField(value: &self._dateStyle) }()
      case 9: try { try decoder.decodeSingularEnumField(value: &self._timeStyle) }()
      case 10: try { try decoder.decodeSingularBoolField(value: &self._ignoresTimeZone) }()
      case 11: try { try decoder.decodeSingularBoolField(value: &self._isRelative) }()
      case 12: try { try decoder.decodeSingularEnumField(value: &self._numberStyle) }()
      case 13: try { try decoder.decodeSingularStringField(value: &self._currencyCode) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.key.isEmpty {
      try visitor.visitSingularStringField(value: self.key, fieldNumber: 1)
    }
    try { if let v = self._value {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._label {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._attributedValue {
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._changeMessage {
      try visitor.visitSingularStringField(value: v, fieldNumber: 5)
    } }()
    if !self.dataDetectorTypes.isEmpty {
      try visitor.visitPackedEnumField(value: self.dataDetectorTypes, fieldNumber: 6)
    }
    try { if let v = self._textAlignment {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 7)
    } }()
    try { if let v = self._dateStyle {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 8)
    } }()
    try { if let v = self._timeStyle {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 9)
    } }()
    try { if let v = self._ignoresTimeZone {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 10)
    } }()
    try { if let v = self._isRelative {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 11)
    } }()
    try { if let v = self._numberStyle {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 12)
    } }()
    try { if let v = self._currencyCode {
      try visitor.visitSingularStringField(value: v, fieldNumber: 13)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: PBPassFieldContent, rhs: PBPassFieldContent) -> Bool {
    if lhs.key != rhs.key {return false}
    if lhs._value != rhs._value {return false}
    if lhs._label != rhs._label {return false}
    if lhs._attributedValue != rhs._attributedValue {return false}
    if lhs._changeMessage != rhs._changeMessage {return false}
    if lhs.dataDetectorTypes != rhs.dataDetectorTypes {return false}
    if lhs._textAlignment != rhs._textAlignment {return false}
    if lhs._dateStyle != rhs._dateStyle {return false}
    if lhs._timeStyle != rhs._timeStyle {return false}
    if lhs._ignoresTimeZone != rhs._ignoresTimeZone {return false}
    if lhs._isRelative != rhs._isRelative {return false}
    if lhs._numberStyle != rhs._numberStyle {return false}
    if lhs._currencyCode != rhs._currencyCode {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
