// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: PassSeat.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// A message that represents the identification of a seat for a transit journey or an event.
struct PBPassSeat: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// A description of the seat, such as A flat bed seat.
  var seatDescription: String = String()

  /// The identifier code for the seat.
  var seatIdentifier: String = String()

  /// The number of the seat.
  var seatNumber: String = String()

  /// The row that contains the seat.
  var seatRow: String = String()

  /// The section that contains the seat.
  var seatSection: String = String()

  /// The aisle that contains the seat.
  var seatAisle: String = String()

  /// The level that contains the seat.
  var seatLevel: String = String()

  /// The type of seat, such as Reserved seating.
  var seatType: String = String()

  /// A color associated with identifying the seat
  var seatSectionColor: PBPassColor {
    get {return _seatSectionColor ?? PBPassColor()}
    set {_seatSectionColor = newValue}
  }
  /// Returns true if `seatSectionColor` has been explicitly set.
  var hasSeatSectionColor: Bool {return self._seatSectionColor != nil}
  /// Clears the value of `seatSectionColor`. Subsequent reads from it will return its default value.
  mutating func clearSeatSectionColor() {self._seatSectionColor = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _seatSectionColor: PBPassColor? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "pass"

extension PBPassSeat: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".PassSeat"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}seat_description\0\u{3}seat_identifier\0\u{3}seat_number\0\u{3}seat_row\0\u{3}seat_section\0\u{3}seat_aisle\0\u{3}seat_level\0\u{3}seat_type\0\u{3}seat_section_color\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.seatDescription) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.seatIdentifier) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.seatNumber) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.seatRow) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.seatSection) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.seatAisle) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.seatLevel) }()
      case 8: try { try decoder.decodeSingularStringField(value: &self.seatType) }()
      case 9: try { try decoder.decodeSingularMessageField(value: &self._seatSectionColor) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.seatDescription.isEmpty {
      try visitor.visitSingularStringField(value: self.seatDescription, fieldNumber: 1)
    }
    if !self.seatIdentifier.isEmpty {
      try visitor.visitSingularStringField(value: self.seatIdentifier, fieldNumber: 2)
    }
    if !self.seatNumber.isEmpty {
      try visitor.visitSingularStringField(value: self.seatNumber, fieldNumber: 3)
    }
    if !self.seatRow.isEmpty {
      try visitor.visitSingularStringField(value: self.seatRow, fieldNumber: 4)
    }
    if !self.seatSection.isEmpty {
      try visitor.visitSingularStringField(value: self.seatSection, fieldNumber: 5)
    }
    if !self.seatAisle.isEmpty {
      try visitor.visitSingularStringField(value: self.seatAisle, fieldNumber: 6)
    }
    if !self.seatLevel.isEmpty {
      try visitor.visitSingularStringField(value: self.seatLevel, fieldNumber: 7)
    }
    if !self.seatType.isEmpty {
      try visitor.visitSingularStringField(value: self.seatType, fieldNumber: 8)
    }
    try { if let v = self._seatSectionColor {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: PBPassSeat, rhs: PBPassSeat) -> Bool {
    if lhs.seatDescription != rhs.seatDescription {return false}
    if lhs.seatIdentifier != rhs.seatIdentifier {return false}
    if lhs.seatNumber != rhs.seatNumber {return false}
    if lhs.seatRow != rhs.seatRow {return false}
    if lhs.seatSection != rhs.seatSection {return false}
    if lhs.seatAisle != rhs.seatAisle {return false}
    if lhs.seatLevel != rhs.seatLevel {return false}
    if lhs.seatType != rhs.seatType {return false}
    if lhs._seatSectionColor != rhs._seatSectionColor {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
