// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: PassTransitType.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

enum PBPassTransitType: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case transitTypeUnspecified // = 0
  case transitTypeAir // = 1
  case transitTypeBoat // = 2
  case transitTypeBus // = 3
  case transitTypeTrain // = 4
  case transitTypeGeneric // = 5
  case UNRECOGNIZED(Int)

  init() {
    self = .transitTypeUnspecified
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .transitTypeUnspecified
    case 1: self = .transitTypeAir
    case 2: self = .transitTypeBoat
    case 3: self = .transitTypeBus
    case 4: self = .transitTypeTrain
    case 5: self = .transitTypeGeneric
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .transitTypeUnspecified: return 0
    case .transitTypeAir: return 1
    case .transitTypeBoat: return 2
    case .transitTypeBus: return 3
    case .transitTypeTrain: return 4
    case .transitTypeGeneric: return 5
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [PBPassTransitType] = [
    .transitTypeUnspecified,
    .transitTypeAir,
    .transitTypeBoat,
    .transitTypeBus,
    .transitTypeTrain,
    .transitTypeGeneric,
  ]

}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension PBPassTransitType: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0TRANSIT_TYPE_UNSPECIFIED\0\u{1}TRANSIT_TYPE_AIR\0\u{1}TRANSIT_TYPE_BOAT\0\u{1}TRANSIT_TYPE_BUS\0\u{1}TRANSIT_TYPE_TRAIN\0\u{1}TRANSIT_TYPE_GENERIC\0")
}
