// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: PassImageSet.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// A collection of images at varying scale factors, representing a single logical image in a pass.
struct PBPassImageSet: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The 1x scale image.
  var times1: PBPassImageFile {
    get {return _times1 ?? PBPassImageFile()}
    set {_times1 = newValue}
  }
  /// Returns true if `times1` has been explicitly set.
  var hasTimes1: Bool {return self._times1 != nil}
  /// Clears the value of `times1`. Subsequent reads from it will return its default value.
  mutating func clearTimes1() {self._times1 = nil}

  /// The 2x scale image.
  var times2: PBPassImageFile {
    get {return _times2 ?? PBPassImageFile()}
    set {_times2 = newValue}
  }
  /// Returns true if `times2` has been explicitly set.
  var hasTimes2: Bool {return self._times2 != nil}
  /// Clears the value of `times2`. Subsequent reads from it will return its default value.
  mutating func clearTimes2() {self._times2 = nil}

  /// The 3x scale image.
  var times3: PBPassImageFile {
    get {return _times3 ?? PBPassImageFile()}
    set {_times3 = newValue}
  }
  /// Returns true if `times3` has been explicitly set.
  var hasTimes3: Bool {return self._times3 != nil}
  /// Clears the value of `times3`. Subsequent reads from it will return its default value.
  mutating func clearTimes3() {self._times3 = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _times1: PBPassImageFile? = nil
  fileprivate var _times2: PBPassImageFile? = nil
  fileprivate var _times3: PBPassImageFile? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "pass"

extension PBPassImageSet: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".PassImageSet"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}times1\0\u{1}times2\0\u{1}times3\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._times1) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._times2) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._times3) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._times1 {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._times2 {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._times3 {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: PBPassImageSet, rhs: PBPassImageSet) -> Bool {
    if lhs._times1 != rhs._times1 {return false}
    if lhs._times2 != rhs._times2 {return false}
    if lhs._times3 != rhs._times3 {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
