// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: PassTextAlignment.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Text Alignment Enum
enum PBPassTextAlignment: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case textAlignmentUnspecified // = 0
  case textAlignmentLeft // = 1
  case textAlignmentCenter // = 2
  case textAlignmentRight // = 3
  case textAlignmentNatural // = 4
  case UNRECOGNIZED(Int)

  init() {
    self = .textAlignmentUnspecified
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .textAlignmentUnspecified
    case 1: self = .textAlignmentLeft
    case 2: self = .textAlignmentCenter
    case 3: self = .textAlignmentRight
    case 4: self = .textAlignmentNatural
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .textAlignmentUnspecified: return 0
    case .textAlignmentLeft: return 1
    case .textAlignmentCenter: return 2
    case .textAlignmentRight: return 3
    case .textAlignmentNatural: return 4
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [PBPassTextAlignment] = [
    .textAlignmentUnspecified,
    .textAlignmentLeft,
    .textAlignmentCenter,
    .textAlignmentRight,
    .textAlignmentNatural,
  ]

}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension PBPassTextAlignment: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0TEXT_ALIGNMENT_UNSPECIFIED\0\u{1}TEXT_ALIGNMENT_LEFT\0\u{1}TEXT_ALIGNMENT_CENTER\0\u{1}TEXT_ALIGNMENT_RIGHT\0\u{1}TEXT_ALIGNMENT_NATURAL\0")
}
