// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: PassPersonName.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// A message that represents a person's name.
struct PBPassPersonName: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The prefix for the person’s name, such as “Dr”.
  var namePrefix: String = String()

  /// The person’s given name; also called the forename or first name in some countries.
  var givenName: String = String()

  /// The person’s middle name.
  var middleName: String = String()

  /// The person’s family name or last name.
  var familyName: String = String()

  /// The suffix for the person’s name, such as “Junior”.
  var nameSuffix: String = String()

  /// The person’s nickname.
  var nickname: String = String()

  /// The phonetic representation of the person’s name.
  var phoneticRepresentation: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "pass"

extension PBPassPersonName: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".PassPersonName"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}name_prefix\0\u{3}given_name\0\u{3}middle_name\0\u{3}family_name\0\u{3}name_suffix\0\u{1}nickname\0\u{3}phonetic_representation\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.namePrefix) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.givenName) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.middleName) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.familyName) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.nameSuffix) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.nickname) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.phoneticRepresentation) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.namePrefix.isEmpty {
      try visitor.visitSingularStringField(value: self.namePrefix, fieldNumber: 1)
    }
    if !self.givenName.isEmpty {
      try visitor.visitSingularStringField(value: self.givenName, fieldNumber: 2)
    }
    if !self.middleName.isEmpty {
      try visitor.visitSingularStringField(value: self.middleName, fieldNumber: 3)
    }
    if !self.familyName.isEmpty {
      try visitor.visitSingularStringField(value: self.familyName, fieldNumber: 4)
    }
    if !self.nameSuffix.isEmpty {
      try visitor.visitSingularStringField(value: self.nameSuffix, fieldNumber: 5)
    }
    if !self.nickname.isEmpty {
      try visitor.visitSingularStringField(value: self.nickname, fieldNumber: 6)
    }
    if !self.phoneticRepresentation.isEmpty {
      try visitor.visitSingularStringField(value: self.phoneticRepresentation, fieldNumber: 7)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: PBPassPersonName, rhs: PBPassPersonName) -> Bool {
    if lhs.namePrefix != rhs.namePrefix {return false}
    if lhs.givenName != rhs.givenName {return false}
    if lhs.middleName != rhs.middleName {return false}
    if lhs.familyName != rhs.familyName {return false}
    if lhs.nameSuffix != rhs.nameSuffix {return false}
    if lhs.nickname != rhs.nickname {return false}
    if lhs.phoneticRepresentation != rhs.phoneticRepresentation {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
