// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: PassDateTimeFormat.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Date/Time Format Enum
enum PBPassDateTimeFormat: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case dateTimeFormatUnspecified // = 0
  case dateTimeFormatNone // = 1
  case dateTimeFormatShort // = 2
  case dateTimeFormatMedium // = 3
  case dateTimeFormatLong // = 4
  case dateTimeFormatFull // = 5
  case UNRECOGNIZED(Int)

  init() {
    self = .dateTimeFormatUnspecified
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .dateTimeFormatUnspecified
    case 1: self = .dateTimeFormatNone
    case 2: self = .dateTimeFormatShort
    case 3: self = .dateTimeFormatMedium
    case 4: self = .dateTimeFormatLong
    case 5: self = .dateTimeFormatFull
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .dateTimeFormatUnspecified: return 0
    case .dateTimeFormatNone: return 1
    case .dateTimeFormatShort: return 2
    case .dateTimeFormatMedium: return 3
    case .dateTimeFormatLong: return 4
    case .dateTimeFormatFull: return 5
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [PBPassDateTimeFormat] = [
    .dateTimeFormatUnspecified,
    .dateTimeFormatNone,
    .dateTimeFormatShort,
    .dateTimeFormatMedium,
    .dateTimeFormatLong,
    .dateTimeFormatFull,
  ]

}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension PBPassDateTimeFormat: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0DATE_TIME_FORMAT_UNSPECIFIED\0\u{1}DATE_TIME_FORMAT_NONE\0\u{1}DATE_TIME_FORMAT_SHORT\0\u{1}DATE_TIME_FORMAT_MEDIUM\0\u{1}DATE_TIME_FORMAT_LONG\0\u{1}DATE_TIME_FORMAT_FULL\0")
}
