// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: PassPackage.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// A message that represents a pass.
struct PBPassPackage: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// A representation of the `pass.json`.
  var pass: PBPass {
    get {return _storage._pass ?? PBPass()}
    set {_uniqueStorage()._pass = newValue}
  }
  /// Returns true if `pass` has been explicitly set.
  var hasPass: Bool {return _storage._pass != nil}
  /// Clears the value of `pass`. Subsequent reads from it will return its default value.
  mutating func clearPass() {_uniqueStorage()._pass = nil}

  /// The background image displayed behind the pass content.
  var background: PBPassImageSet {
    get {return _storage._background ?? PBPassImageSet()}
    set {_uniqueStorage()._background = newValue}
  }
  /// Returns true if `background` has been explicitly set.
  var hasBackground: Bool {return _storage._background != nil}
  /// Clears the value of `background`. Subsequent reads from it will return its default value.
  mutating func clearBackground() {_uniqueStorage()._background = nil}

  /// The artwork image for poster event tickets.
  var artwork: PBPassImageSet {
    get {return _storage._artwork ?? PBPassImageSet()}
    set {_uniqueStorage()._artwork = newValue}
  }
  /// Returns true if `artwork` has been explicitly set.
  var hasArtwork: Bool {return _storage._artwork != nil}
  /// Clears the value of `artwork`. Subsequent reads from it will return its default value.
  mutating func clearArtwork() {_uniqueStorage()._artwork = nil}

  /// The footer image displayed at the bottom of the pass.
  var footer: PBPassImageSet {
    get {return _storage._footer ?? PBPassImageSet()}
    set {_uniqueStorage()._footer = newValue}
  }
  /// Returns true if `footer` has been explicitly set.
  var hasFooter: Bool {return _storage._footer != nil}
  /// Clears the value of `footer`. Subsequent reads from it will return its default value.
  mutating func clearFooter() {_uniqueStorage()._footer = nil}

  /// The pass icon.
  var icon: PBPassImageSet {
    get {return _storage._icon ?? PBPassImageSet()}
    set {_uniqueStorage()._icon = newValue}
  }
  /// Returns true if `icon` has been explicitly set.
  var hasIcon: Bool {return _storage._icon != nil}
  /// Clears the value of `icon`. Subsequent reads from it will return its default value.
  mutating func clearIcon() {_uniqueStorage()._icon = nil}

  /// The logo image displayed on the top of the pass.
  var logo: PBPassImageSet {
    get {return _storage._logo ?? PBPassImageSet()}
    set {_uniqueStorage()._logo = newValue}
  }
  /// Returns true if `logo` has been explicitly set.
  var hasLogo: Bool {return _storage._logo != nil}
  /// Clears the value of `logo`. Subsequent reads from it will return its default value.
  mutating func clearLogo() {_uniqueStorage()._logo = nil}

  /// The primary logo displayed on the top of poster passes.
  var primaryLogo: PBPassImageSet {
    get {return _storage._primaryLogo ?? PBPassImageSet()}
    set {_uniqueStorage()._primaryLogo = newValue}
  }
  /// Returns true if `primaryLogo` has been explicitly set.
  var hasPrimaryLogo: Bool {return _storage._primaryLogo != nil}
  /// Clears the value of `primaryLogo`. Subsequent reads from it will return its default value.
  mutating func clearPrimaryLogo() {_uniqueStorage()._primaryLogo = nil}

  /// The secondary logo on some poster passes.
  var secondaryLogo: PBPassImageSet {
    get {return _storage._secondaryLogo ?? PBPassImageSet()}
    set {_uniqueStorage()._secondaryLogo = newValue}
  }
  /// Returns true if `secondaryLogo` has been explicitly set.
  var hasSecondaryLogo: Bool {return _storage._secondaryLogo != nil}
  /// Clears the value of `secondaryLogo`. Subsequent reads from it will return its default value.
  mutating func clearSecondaryLogo() {_uniqueStorage()._secondaryLogo = nil}

  /// The strip image displayed across the pass.
  var strip: PBPassImageSet {
    get {return _storage._strip ?? PBPassImageSet()}
    set {_uniqueStorage()._strip = newValue}
  }
  /// Returns true if `strip` has been explicitly set.
  var hasStrip: Bool {return _storage._strip != nil}
  /// Clears the value of `strip`. Subsequent reads from it will return its default value.
  mutating func clearStrip() {_uniqueStorage()._strip = nil}

  /// The thumbnail image for the pass.
  var thumbnail: PBPassImageSet {
    get {return _storage._thumbnail ?? PBPassImageSet()}
    set {_uniqueStorage()._thumbnail = newValue}
  }
  /// Returns true if `thumbnail` has been explicitly set.
  var hasThumbnail: Bool {return _storage._thumbnail != nil}
  /// Clears the value of `thumbnail`. Subsequent reads from it will return its default value.
  mutating func clearThumbnail() {_uniqueStorage()._thumbnail = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "pass"

extension PBPassPackage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".PassPackage"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}pass\0\u{1}background\0\u{1}artwork\0\u{1}footer\0\u{1}icon\0\u{1}logo\0\u{1}primaryLogo\0\u{1}secondaryLogo\0\u{1}strip\0\u{1}thumbnail\0")

  fileprivate class _StorageClass {
    var _pass: PBPass? = nil
    var _background: PBPassImageSet? = nil
    var _artwork: PBPassImageSet? = nil
    var _footer: PBPassImageSet? = nil
    var _icon: PBPassImageSet? = nil
    var _logo: PBPassImageSet? = nil
    var _primaryLogo: PBPassImageSet? = nil
    var _secondaryLogo: PBPassImageSet? = nil
    var _strip: PBPassImageSet? = nil
    var _thumbnail: PBPassImageSet? = nil

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _pass = source._pass
      _background = source._background
      _artwork = source._artwork
      _footer = source._footer
      _icon = source._icon
      _logo = source._logo
      _primaryLogo = source._primaryLogo
      _secondaryLogo = source._secondaryLogo
      _strip = source._strip
      _thumbnail = source._thumbnail
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularMessageField(value: &_storage._pass) }()
        case 2: try { try decoder.decodeSingularMessageField(value: &_storage._background) }()
        case 3: try { try decoder.decodeSingularMessageField(value: &_storage._artwork) }()
        case 4: try { try decoder.decodeSingularMessageField(value: &_storage._footer) }()
        case 5: try { try decoder.decodeSingularMessageField(value: &_storage._icon) }()
        case 6: try { try decoder.decodeSingularMessageField(value: &_storage._logo) }()
        case 7: try { try decoder.decodeSingularMessageField(value: &_storage._primaryLogo) }()
        case 8: try { try decoder.decodeSingularMessageField(value: &_storage._secondaryLogo) }()
        case 9: try { try decoder.decodeSingularMessageField(value: &_storage._strip) }()
        case 10: try { try decoder.decodeSingularMessageField(value: &_storage._thumbnail) }()
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._pass {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      } }()
      try { if let v = _storage._background {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      } }()
      try { if let v = _storage._artwork {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
      } }()
      try { if let v = _storage._footer {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
      } }()
      try { if let v = _storage._icon {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
      } }()
      try { if let v = _storage._logo {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
      } }()
      try { if let v = _storage._primaryLogo {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
      } }()
      try { if let v = _storage._secondaryLogo {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
      } }()
      try { if let v = _storage._strip {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
      } }()
      try { if let v = _storage._thumbnail {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: PBPassPackage, rhs: PBPassPackage) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._pass != rhs_storage._pass {return false}
        if _storage._background != rhs_storage._background {return false}
        if _storage._artwork != rhs_storage._artwork {return false}
        if _storage._footer != rhs_storage._footer {return false}
        if _storage._icon != rhs_storage._icon {return false}
        if _storage._logo != rhs_storage._logo {return false}
        if _storage._primaryLogo != rhs_storage._primaryLogo {return false}
        if _storage._secondaryLogo != rhs_storage._secondaryLogo {return false}
        if _storage._strip != rhs_storage._strip {return false}
        if _storage._thumbnail != rhs_storage._thumbnail {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
