// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: UpcomingPassInformationEntry.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Upcoming Pass Information Entry
/// An entry that represents upcoming event or pass information that can be displayed
/// in the Additional Info section below a pass.
struct PBUpcomingPassInformationEntry: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// (Required) A string that uniquely identifies the upcoming pass information entry.
  /// The identifier needs to be unique for each upcoming information entry.
  var identifier: String {
    get {return _storage._identifier}
    set {_uniqueStorage()._identifier = newValue}
  }

  /// (Required) The name of the upcoming pass information entry.
  var name: String {
    get {return _storage._name}
    set {_uniqueStorage()._name = newValue}
  }

  /// (Required) The type of upcoming pass information entry.
  /// The only value currently supported is "event".
  var type: String {
    get {return _storage._type}
    set {_uniqueStorage()._type = newValue}
  }

  /// A collection of URLs used to populate UI elements in the details view.
  var urls: PBUpcomingPassInformationEntry.URLs {
    get {return _storage._urls ?? PBUpcomingPassInformationEntry.URLs()}
    set {_uniqueStorage()._urls = newValue}
  }
  /// Returns true if `urls` has been explicitly set.
  var hasUrls: Bool {return _storage._urls != nil}
  /// Clears the value of `urls`. Subsequent reads from it will return its default value.
  mutating func clearUrls() {_uniqueStorage()._urls = nil}

  /// An array of App Store identifiers for apps associated with the upcoming pass information entry.
  /// The associated app on a device is the first item in the array that's compatible with that device.
  /// This key works only for upcoming pass information entries for an event.
  var auxiliaryStoreIdentifiers: [Int32] {
    get {return _storage._auxiliaryStoreIdentifiers}
    set {_uniqueStorage()._auxiliaryStoreIdentifiers = newValue}
  }

  /// The fields of information displayed on the Additional Info section below a pass.
  var additionalInfoFields: PBPassFieldsList {
    get {return _storage._additionalInfoFields ?? PBPassFieldsList()}
    set {_uniqueStorage()._additionalInfoFields = newValue}
  }
  /// Returns true if `additionalInfoFields` has been explicitly set.
  var hasAdditionalInfoFields: Bool {return _storage._additionalInfoFields != nil}
  /// Clears the value of `additionalInfoFields`. Subsequent reads from it will return its default value.
  mutating func clearAdditionalInfoFields() {_uniqueStorage()._additionalInfoFields = nil}

  /// The fields of information displayed on the details view of the upcoming pass information entry.
  var backFields: PBPassFieldsList {
    get {return _storage._backFields ?? PBPassFieldsList()}
    set {_uniqueStorage()._backFields = newValue}
  }
  /// Returns true if `backFields` has been explicitly set.
  var hasBackFields: Bool {return _storage._backFields != nil}
  /// Clears the value of `backFields`. Subsequent reads from it will return its default value.
  mutating func clearBackFields() {_uniqueStorage()._backFields = nil}

  /// The customization to apply to the pkpasstemplate.
  var fieldCustomization: PBPassFieldsTemplateCustomization {
    get {return _storage._fieldCustomization ?? PBPassFieldsTemplateCustomization()}
    set {_uniqueStorage()._fieldCustomization = newValue}
  }
  /// Returns true if `fieldCustomization` has been explicitly set.
  var hasFieldCustomization: Bool {return _storage._fieldCustomization != nil}
  /// Clears the value of `fieldCustomization`. Subsequent reads from it will return its default value.
  mutating func clearFieldCustomization() {_uniqueStorage()._fieldCustomization = nil}

  /// Information about the start and end time of the upcoming pass information entry.
  /// If omitted, the entry is labeled as TBD.
  var dateInformation: PBUpcomingPassInformationEntry.DateInformation {
    get {return _storage._dateInformation ?? PBUpcomingPassInformationEntry.DateInformation()}
    set {_uniqueStorage()._dateInformation = newValue}
  }
  /// Returns true if `dateInformation` has been explicitly set.
  var hasDateInformation: Bool {return _storage._dateInformation != nil}
  /// Clears the value of `dateInformation`. Subsequent reads from it will return its default value.
  mutating func clearDateInformation() {_uniqueStorage()._dateInformation = nil}

  /// A collection of image names used to populate images in the details view.
  var images: PBUpcomingPassInformationEntry.Images {
    get {return _storage._images ?? PBUpcomingPassInformationEntry.Images()}
    set {_uniqueStorage()._images = newValue}
  }
  /// Returns true if `images` has been explicitly set.
  var hasImages: Bool {return _storage._images != nil}
  /// Clears the value of `images`. Subsequent reads from it will return its default value.
  mutating func clearImages() {_uniqueStorage()._images = nil}

  /// Indicates whether the upcoming pass information entry is currently active.
  /// The default value is false.
  var isActive: Bool {
    get {return _storage._isActive}
    set {_uniqueStorage()._isActive = newValue}
  }

  /// The semantic, machine-readable metadata about the upcoming pass information entry.
  var semantics: PBPassSemantics {
    get {return _storage._semantics ?? PBPassSemantics()}
    set {_uniqueStorage()._semantics = newValue}
  }
  /// Returns true if `semantics` has been explicitly set.
  var hasSemantics: Bool {return _storage._semantics != nil}
  /// Clears the value of `semantics`. Subsequent reads from it will return its default value.
  mutating func clearSemantics() {_uniqueStorage()._semantics = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  /// A collection of URLs used to populate UI elements in the details view.
  struct URLs: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// A URL that links to your or the venue's accessibility content.
    var accessibilityURL: String {
      get {return _accessibilityURL ?? String()}
      set {_accessibilityURL = newValue}
    }
    /// Returns true if `accessibilityURL` has been explicitly set.
    var hasAccessibilityURL: Bool {return self._accessibilityURL != nil}
    /// Clears the value of `accessibilityURL`. Subsequent reads from it will return its default value.
    mutating func clearAccessibilityURL() {self._accessibilityURL = nil}

    /// A URL that links to experiences that you can add on to your ticket or that allows you to access your
    /// existing pre-purchased or preloaded add-on experiences, including any necessary QR or barcode links.
    var addOnURL: String {
      get {return _addOnURL ?? String()}
      set {_addOnURL = newValue}
    }
    /// Returns true if `addOnURL` has been explicitly set.
    var hasAddOnURL: Bool {return self._addOnURL != nil}
    /// Clears the value of `addOnURL`. Subsequent reads from it will return its default value.
    mutating func clearAddOnURL() {self._addOnURL = nil}

    /// A URL that links out to the bag policy of the venue.
    var bagPolicyURL: String {
      get {return _bagPolicyURL ?? String()}
      set {_bagPolicyURL = newValue}
    }
    /// Returns true if `bagPolicyURL` has been explicitly set.
    var hasBagPolicyURL: Bool {return self._bagPolicyURL != nil}
    /// Clears the value of `bagPolicyURL`. Subsequent reads from it will return its default value.
    mutating func clearBagPolicyURL() {self._bagPolicyURL = nil}

    /// The preferred email address to contact the venue, event, or issuer.
    var contactVenueEmail: String {
      get {return _contactVenueEmail ?? String()}
      set {_contactVenueEmail = newValue}
    }
    /// Returns true if `contactVenueEmail` has been explicitly set.
    var hasContactVenueEmail: Bool {return self._contactVenueEmail != nil}
    /// Clears the value of `contactVenueEmail`. Subsequent reads from it will return its default value.
    mutating func clearContactVenueEmail() {self._contactVenueEmail = nil}

    /// The preferred phone number to contact the venue, event, or issuer.
    var contactVenuePhoneNumber: String {
      get {return _contactVenuePhoneNumber ?? String()}
      set {_contactVenuePhoneNumber = newValue}
    }
    /// Returns true if `contactVenuePhoneNumber` has been explicitly set.
    var hasContactVenuePhoneNumber: Bool {return self._contactVenuePhoneNumber != nil}
    /// Clears the value of `contactVenuePhoneNumber`. Subsequent reads from it will return its default value.
    mutating func clearContactVenuePhoneNumber() {self._contactVenuePhoneNumber = nil}

    /// A URL that links the user to the website of the venue, event, or issuer.
    var contactVenueWebsite: String {
      get {return _contactVenueWebsite ?? String()}
      set {_contactVenueWebsite = newValue}
    }
    /// Returns true if `contactVenueWebsite` has been explicitly set.
    var hasContactVenueWebsite: Bool {return self._contactVenueWebsite != nil}
    /// Clears the value of `contactVenueWebsite`. Subsequent reads from it will return its default value.
    mutating func clearContactVenueWebsite() {self._contactVenueWebsite = nil}

    /// A URL that links to content you have about getting to the venue.
    var directionsInformationURL: String {
      get {return _directionsInformationURL ?? String()}
      set {_directionsInformationURL = newValue}
    }
    /// Returns true if `directionsInformationURL` has been explicitly set.
    var hasDirectionsInformationURL: Bool {return self._directionsInformationURL != nil}
    /// Clears the value of `directionsInformationURL`. Subsequent reads from it will return its default value.
    mutating func clearDirectionsInformationURL() {self._directionsInformationURL = nil}

    /// A URL that links to order merchandise for the specific event.
    var merchandiseURL: String {
      get {return _merchandiseURL ?? String()}
      set {_merchandiseURL = newValue}
    }
    /// Returns true if `merchandiseURL` has been explicitly set.
    var hasMerchandiseURL: Bool {return self._merchandiseURL != nil}
    /// Clears the value of `merchandiseURL`. Subsequent reads from it will return its default value.
    mutating func clearMerchandiseURL() {self._merchandiseURL = nil}

    /// A URL that links out to the food-ordering page for the venue.
    var orderFoodURL: String {
      get {return _orderFoodURL ?? String()}
      set {_orderFoodURL = newValue}
    }
    /// Returns true if `orderFoodURL` has been explicitly set.
    var hasOrderFoodURL: Bool {return self._orderFoodURL != nil}
    /// Clears the value of `orderFoodURL`. Subsequent reads from it will return its default value.
    mutating func clearOrderFoodURL() {self._orderFoodURL = nil}

    /// A URL that links to any information you have about parking.
    var parkingInformationURL: String {
      get {return _parkingInformationURL ?? String()}
      set {_parkingInformationURL = newValue}
    }
    /// Returns true if `parkingInformationURL` has been explicitly set.
    var hasParkingInformationURL: Bool {return self._parkingInformationURL != nil}
    /// Clears the value of `parkingInformationURL`. Subsequent reads from it will return its default value.
    mutating func clearParkingInformationURL() {self._parkingInformationURL = nil}

    /// A URL that links to your experience to buy or access prepaid parking or general parking information.
    var purchaseParkingURL: String {
      get {return _purchaseParkingURL ?? String()}
      set {_purchaseParkingURL = newValue}
    }
    /// Returns true if `purchaseParkingURL` has been explicitly set.
    var hasPurchaseParkingURL: Bool {return self._purchaseParkingURL != nil}
    /// Clears the value of `purchaseParkingURL`. Subsequent reads from it will return its default value.
    mutating func clearPurchaseParkingURL() {self._purchaseParkingURL = nil}

    /// A URL that launches the user into the issuer's flow for selling their current ticket.
    var sellURL: String {
      get {return _sellURL ?? String()}
      set {_sellURL = newValue}
    }
    /// Returns true if `sellURL` has been explicitly set.
    var hasSellURL: Bool {return self._sellURL != nil}
    /// Clears the value of `sellURL`. Subsequent reads from it will return its default value.
    mutating func clearSellURL() {self._sellURL = nil}

    /// A URL that launches the user into the issuer's flow for transferring the current ticket.
    var transferURL: String {
      get {return _transferURL ?? String()}
      set {_transferURL = newValue}
    }
    /// Returns true if `transferURL` has been explicitly set.
    var hasTransferURL: Bool {return self._transferURL != nil}
    /// Clears the value of `transferURL`. Subsequent reads from it will return its default value.
    mutating func clearTransferURL() {self._transferURL = nil}

    /// A URL that links to documentation you have about public or private transit to the venue.
    var transitInformationURL: String {
      get {return _transitInformationURL ?? String()}
      set {_transitInformationURL = newValue}
    }
    /// Returns true if `transitInformationURL` has been explicitly set.
    var hasTransitInformationURL: Bool {return self._transitInformationURL != nil}
    /// Clears the value of `transitInformationURL`. Subsequent reads from it will return its default value.
    mutating func clearTransitInformationURL() {self._transitInformationURL = nil}

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}

    fileprivate var _accessibilityURL: String? = nil
    fileprivate var _addOnURL: String? = nil
    fileprivate var _bagPolicyURL: String? = nil
    fileprivate var _contactVenueEmail: String? = nil
    fileprivate var _contactVenuePhoneNumber: String? = nil
    fileprivate var _contactVenueWebsite: String? = nil
    fileprivate var _directionsInformationURL: String? = nil
    fileprivate var _merchandiseURL: String? = nil
    fileprivate var _orderFoodURL: String? = nil
    fileprivate var _parkingInformationURL: String? = nil
    fileprivate var _purchaseParkingURL: String? = nil
    fileprivate var _sellURL: String? = nil
    fileprivate var _transferURL: String? = nil
    fileprivate var _transitInformationURL: String? = nil
  }

  /// DateInformation - Information about the start and end time of the upcoming pass information entry
  struct DateInformation: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// The start date of the upcoming pass information entry.
    /// If omitted, the entry lists the Time and Date as TBD.
    /// Unix timestamp in seconds.
    var date: SwiftProtobuf.Google_Protobuf_Timestamp {
      get {return _date ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
      set {_date = newValue}
    }
    /// Returns true if `date` has been explicitly set.
    var hasDate: Bool {return self._date != nil}
    /// Clears the value of `date`. Subsequent reads from it will return its default value.
    mutating func clearDate() {self._date = nil}

    /// Indicates whether the entry should ignore the time components of the date.
    var ignoreTimeComponents: Bool = false

    /// Indicates whether the entry spans the entire day and that the time components should be ignored.
    var isAllDay: Bool = false

    /// Indicates whether the provided time of the event hasn't been announced (commonly referred to as TBA).
    var isUnannounced: Bool = false

    /// Indicates whether the provided time of the event hasn't been determined (commonly referred to as TBD).
    var isUndetermined: Bool = false

    /// The time zone to adjust the date into. If omitted, the entry uses the current time zone of the device.
    /// This could be represented as a timezone identifier string (e.g., "America/New_York") or Unix timestamp.
    /// Using string for timezone identifier.
    var timeZone: String = String()

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}

    fileprivate var _date: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
  }

  /// A collection of image names used to populate images in the details view
  struct Images: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// The name of the image file used for the header image on the details screen.
    /// This can be a remote asset.
    var headerImage: PBUpcomingPassInformationEntry.Image {
      get {return _headerImage ?? PBUpcomingPassInformationEntry.Image()}
      set {_headerImage = newValue}
    }
    /// Returns true if `headerImage` has been explicitly set.
    var hasHeaderImage: Bool {return self._headerImage != nil}
    /// Clears the value of `headerImage`. Subsequent reads from it will return its default value.
    mutating func clearHeaderImage() {self._headerImage = nil}

    /// The name of the image file used for the venue map in the event guide for each upcoming pass information
    /// entry. This can be a remote asset and is available for event entries.
    var venueMap: PBUpcomingPassInformationEntry.Image {
      get {return _venueMap ?? PBUpcomingPassInformationEntry.Image()}
      set {_venueMap = newValue}
    }
    /// Returns true if `venueMap` has been explicitly set.
    var hasVenueMap: Bool {return self._venueMap != nil}
    /// Clears the value of `venueMap`. Subsequent reads from it will return its default value.
    mutating func clearVenueMap() {self._venueMap = nil}

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}

    fileprivate var _headerImage: PBUpcomingPassInformationEntry.Image? = nil
    fileprivate var _venueMap: PBUpcomingPassInformationEntry.Image? = nil
  }

  /// An object that represents the image shown within the detail views of upcoming pass information entries
  struct Image: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// A list of URLs used to retrieve an image. The upcoming pass information entry uses the item that best
    /// matches the device's scale.
    var urls: [PBUpcomingPassInformationEntry.ImageURLEntry] = []

    /// Indicates whether to use the local equivalent image instead of the image specified by URLs.
    var reuseExisting: Bool = false

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}
  }

  /// An object that represents the image specifications for the upcoming pass information entry
  struct ImageURLEntry: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// (Required) The SHA256 hash of the image.
    var sha256: String = String()

    /// (Required) The URL that points to the image asset to be downloaded. This must be an https link.
    var url: String = String()

    /// The scale of the image. If unspecified, defaults to 1.
    var scale: Double = 0

    /// Size of the image asset in bytes. The maximum allowed size is 2 megabytes (2,097,152 bytes).
    var size: Int32 = 0

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}
  }

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "pass"

extension PBUpcomingPassInformationEntry: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".UpcomingPassInformationEntry"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}identifier\0\u{1}name\0\u{1}type\0\u{1}urls\0\u{3}additional_info_fields\0\u{3}auxiliary_store_identifiers\0\u{3}back_fields\0\u{3}field_customization\0\u{3}date_information\0\u{1}images\0\u{3}is_active\0\u{1}semantics\0")

  fileprivate class _StorageClass {
    var _identifier: String = String()
    var _name: String = String()
    var _type: String = String()
    var _urls: PBUpcomingPassInformationEntry.URLs? = nil
    var _auxiliaryStoreIdentifiers: [Int32] = []
    var _additionalInfoFields: PBPassFieldsList? = nil
    var _backFields: PBPassFieldsList? = nil
    var _fieldCustomization: PBPassFieldsTemplateCustomization? = nil
    var _dateInformation: PBUpcomingPassInformationEntry.DateInformation? = nil
    var _images: PBUpcomingPassInformationEntry.Images? = nil
    var _isActive: Bool = false
    var _semantics: PBPassSemantics? = nil

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _identifier = source._identifier
      _name = source._name
      _type = source._type
      _urls = source._urls
      _auxiliaryStoreIdentifiers = source._auxiliaryStoreIdentifiers
      _additionalInfoFields = source._additionalInfoFields
      _backFields = source._backFields
      _fieldCustomization = source._fieldCustomization
      _dateInformation = source._dateInformation
      _images = source._images
      _isActive = source._isActive
      _semantics = source._semantics
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularStringField(value: &_storage._identifier) }()
        case 2: try { try decoder.decodeSingularStringField(value: &_storage._name) }()
        case 3: try { try decoder.decodeSingularStringField(value: &_storage._type) }()
        case 4: try { try decoder.decodeSingularMessageField(value: &_storage._urls) }()
        case 5: try { try decoder.decodeSingularMessageField(value: &_storage._additionalInfoFields) }()
        case 6: try { try decoder.decodeRepeatedInt32Field(value: &_storage._auxiliaryStoreIdentifiers) }()
        case 7: try { try decoder.decodeSingularMessageField(value: &_storage._backFields) }()
        case 8: try { try decoder.decodeSingularMessageField(value: &_storage._fieldCustomization) }()
        case 9: try { try decoder.decodeSingularMessageField(value: &_storage._dateInformation) }()
        case 10: try { try decoder.decodeSingularMessageField(value: &_storage._images) }()
        case 11: try { try decoder.decodeSingularBoolField(value: &_storage._isActive) }()
        case 12: try { try decoder.decodeSingularMessageField(value: &_storage._semantics) }()
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if !_storage._identifier.isEmpty {
        try visitor.visitSingularStringField(value: _storage._identifier, fieldNumber: 1)
      }
      if !_storage._name.isEmpty {
        try visitor.visitSingularStringField(value: _storage._name, fieldNumber: 2)
      }
      if !_storage._type.isEmpty {
        try visitor.visitSingularStringField(value: _storage._type, fieldNumber: 3)
      }
      try { if let v = _storage._urls {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
      } }()
      try { if let v = _storage._additionalInfoFields {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
      } }()
      if !_storage._auxiliaryStoreIdentifiers.isEmpty {
        try visitor.visitPackedInt32Field(value: _storage._auxiliaryStoreIdentifiers, fieldNumber: 6)
      }
      try { if let v = _storage._backFields {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
      } }()
      try { if let v = _storage._fieldCustomization {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
      } }()
      try { if let v = _storage._dateInformation {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
      } }()
      try { if let v = _storage._images {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
      } }()
      if _storage._isActive != false {
        try visitor.visitSingularBoolField(value: _storage._isActive, fieldNumber: 11)
      }
      try { if let v = _storage._semantics {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 12)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: PBUpcomingPassInformationEntry, rhs: PBUpcomingPassInformationEntry) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._identifier != rhs_storage._identifier {return false}
        if _storage._name != rhs_storage._name {return false}
        if _storage._type != rhs_storage._type {return false}
        if _storage._urls != rhs_storage._urls {return false}
        if _storage._auxiliaryStoreIdentifiers != rhs_storage._auxiliaryStoreIdentifiers {return false}
        if _storage._additionalInfoFields != rhs_storage._additionalInfoFields {return false}
        if _storage._backFields != rhs_storage._backFields {return false}
        if _storage._fieldCustomization != rhs_storage._fieldCustomization {return false}
        if _storage._dateInformation != rhs_storage._dateInformation {return false}
        if _storage._images != rhs_storage._images {return false}
        if _storage._isActive != rhs_storage._isActive {return false}
        if _storage._semantics != rhs_storage._semantics {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension PBUpcomingPassInformationEntry.URLs: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = PBUpcomingPassInformationEntry.protoMessageName + ".URLs"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}accessibility_url\0\u{3}add_on_url\0\u{3}bag_policy_url\0\u{3}contact_venue_email\0\u{3}contact_venue_phone_number\0\u{3}contact_venue_website\0\u{3}directions_information_url\0\u{3}merchandise_url\0\u{3}order_food_url\0\u{3}parking_information_url\0\u{3}purchase_parking_url\0\u{3}sell_url\0\u{3}transfer_url\0\u{3}transit_information_url\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._accessibilityURL) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._addOnURL) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._bagPolicyURL) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self._contactVenueEmail) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self._contactVenuePhoneNumber) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self._contactVenueWebsite) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self._directionsInformationURL) }()
      case 8: try { try decoder.decodeSingularStringField(value: &self._merchandiseURL) }()
      case 9: try { try decoder.decodeSingularStringField(value: &self._orderFoodURL) }()
      case 10: try { try decoder.decodeSingularStringField(value: &self._parkingInformationURL) }()
      case 11: try { try decoder.decodeSingularStringField(value: &self._purchaseParkingURL) }()
      case 12: try { try decoder.decodeSingularStringField(value: &self._sellURL) }()
      case 13: try { try decoder.decodeSingularStringField(value: &self._transferURL) }()
      case 14: try { try decoder.decodeSingularStringField(value: &self._transitInformationURL) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._accessibilityURL {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._addOnURL {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._bagPolicyURL {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._contactVenueEmail {
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._contactVenuePhoneNumber {
      try visitor.visitSingularStringField(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._contactVenueWebsite {
      try visitor.visitSingularStringField(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._directionsInformationURL {
      try visitor.visitSingularStringField(value: v, fieldNumber: 7)
    } }()
    try { if let v = self._merchandiseURL {
      try visitor.visitSingularStringField(value: v, fieldNumber: 8)
    } }()
    try { if let v = self._orderFoodURL {
      try visitor.visitSingularStringField(value: v, fieldNumber: 9)
    } }()
    try { if let v = self._parkingInformationURL {
      try visitor.visitSingularStringField(value: v, fieldNumber: 10)
    } }()
    try { if let v = self._purchaseParkingURL {
      try visitor.visitSingularStringField(value: v, fieldNumber: 11)
    } }()
    try { if let v = self._sellURL {
      try visitor.visitSingularStringField(value: v, fieldNumber: 12)
    } }()
    try { if let v = self._transferURL {
      try visitor.visitSingularStringField(value: v, fieldNumber: 13)
    } }()
    try { if let v = self._transitInformationURL {
      try visitor.visitSingularStringField(value: v, fieldNumber: 14)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: PBUpcomingPassInformationEntry.URLs, rhs: PBUpcomingPassInformationEntry.URLs) -> Bool {
    if lhs._accessibilityURL != rhs._accessibilityURL {return false}
    if lhs._addOnURL != rhs._addOnURL {return false}
    if lhs._bagPolicyURL != rhs._bagPolicyURL {return false}
    if lhs._contactVenueEmail != rhs._contactVenueEmail {return false}
    if lhs._contactVenuePhoneNumber != rhs._contactVenuePhoneNumber {return false}
    if lhs._contactVenueWebsite != rhs._contactVenueWebsite {return false}
    if lhs._directionsInformationURL != rhs._directionsInformationURL {return false}
    if lhs._merchandiseURL != rhs._merchandiseURL {return false}
    if lhs._orderFoodURL != rhs._orderFoodURL {return false}
    if lhs._parkingInformationURL != rhs._parkingInformationURL {return false}
    if lhs._purchaseParkingURL != rhs._purchaseParkingURL {return false}
    if lhs._sellURL != rhs._sellURL {return false}
    if lhs._transferURL != rhs._transferURL {return false}
    if lhs._transitInformationURL != rhs._transitInformationURL {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension PBUpcomingPassInformationEntry.DateInformation: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = PBUpcomingPassInformationEntry.protoMessageName + ".DateInformation"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}date\0\u{3}ignore_time_components\0\u{3}is_all_day\0\u{3}is_unannounced\0\u{3}is_undetermined\0\u{3}time_zone\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._date) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.ignoreTimeComponents) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.isAllDay) }()
      case 4: try { try decoder.decodeSingularBoolField(value: &self.isUnannounced) }()
      case 5: try { try decoder.decodeSingularBoolField(value: &self.isUndetermined) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.timeZone) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._date {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if self.ignoreTimeComponents != false {
      try visitor.visitSingularBoolField(value: self.ignoreTimeComponents, fieldNumber: 2)
    }
    if self.isAllDay != false {
      try visitor.visitSingularBoolField(value: self.isAllDay, fieldNumber: 3)
    }
    if self.isUnannounced != false {
      try visitor.visitSingularBoolField(value: self.isUnannounced, fieldNumber: 4)
    }
    if self.isUndetermined != false {
      try visitor.visitSingularBoolField(value: self.isUndetermined, fieldNumber: 5)
    }
    if !self.timeZone.isEmpty {
      try visitor.visitSingularStringField(value: self.timeZone, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: PBUpcomingPassInformationEntry.DateInformation, rhs: PBUpcomingPassInformationEntry.DateInformation) -> Bool {
    if lhs._date != rhs._date {return false}
    if lhs.ignoreTimeComponents != rhs.ignoreTimeComponents {return false}
    if lhs.isAllDay != rhs.isAllDay {return false}
    if lhs.isUnannounced != rhs.isUnannounced {return false}
    if lhs.isUndetermined != rhs.isUndetermined {return false}
    if lhs.timeZone != rhs.timeZone {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension PBUpcomingPassInformationEntry.Images: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = PBUpcomingPassInformationEntry.protoMessageName + ".Images"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}header_image\0\u{3}venue_map\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._headerImage) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._venueMap) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._headerImage {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._venueMap {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: PBUpcomingPassInformationEntry.Images, rhs: PBUpcomingPassInformationEntry.Images) -> Bool {
    if lhs._headerImage != rhs._headerImage {return false}
    if lhs._venueMap != rhs._venueMap {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension PBUpcomingPassInformationEntry.Image: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = PBUpcomingPassInformationEntry.protoMessageName + ".Image"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}urls\0\u{3}reuse_existing\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.urls) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.reuseExisting) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.urls.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.urls, fieldNumber: 1)
    }
    if self.reuseExisting != false {
      try visitor.visitSingularBoolField(value: self.reuseExisting, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: PBUpcomingPassInformationEntry.Image, rhs: PBUpcomingPassInformationEntry.Image) -> Bool {
    if lhs.urls != rhs.urls {return false}
    if lhs.reuseExisting != rhs.reuseExisting {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension PBUpcomingPassInformationEntry.ImageURLEntry: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = PBUpcomingPassInformationEntry.protoMessageName + ".ImageURLEntry"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}sha256\0\u{1}url\0\u{1}scale\0\u{1}size\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.sha256) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.url) }()
      case 3: try { try decoder.decodeSingularDoubleField(value: &self.scale) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self.size) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.sha256.isEmpty {
      try visitor.visitSingularStringField(value: self.sha256, fieldNumber: 1)
    }
    if !self.url.isEmpty {
      try visitor.visitSingularStringField(value: self.url, fieldNumber: 2)
    }
    if self.scale.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.scale, fieldNumber: 3)
    }
    if self.size != 0 {
      try visitor.visitSingularInt32Field(value: self.size, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: PBUpcomingPassInformationEntry.ImageURLEntry, rhs: PBUpcomingPassInformationEntry.ImageURLEntry) -> Bool {
    if lhs.sha256 != rhs.sha256 {return false}
    if lhs.url != rhs.url {return false}
    if lhs.scale != rhs.scale {return false}
    if lhs.size != rhs.size {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
